### ISSUE TITLE
Scoreboard issue with /d command

### ISSUE THREAD

**Issue by jenks1999** [libraryaddict/LibsDisguises#105]
[12:31:43 WARN]: [LibsDisguises] Task #448 for LibsDisguises v9.0 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/scoreboard/Team$Option
        at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1031) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:746) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-604e046-69e196f]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot_server.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot_server.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-604e046-69e196f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

This error is thrown using featherboard and the disguise doesn't function at all.

**Comment by NavidK0** [comment]
Are you using the latest version of Spigot 1.9?

**Comment by jenks1999** [comment]
This server is running CraftBukkit version git-Spigot-604e046-69e196f (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

thats what i am running at the moment.

**Comment by NavidK0** [comment]
Have you updated featherboard? And does the error occur without featherboard?

**Comment by libraryaddict** [comment]
Confirm still a bug

**Comment by jenks1999** [comment]
i the plugin now as i got fed up with the spam crashing it was invoking. So i dont know anymore. Sorry
