### ISSUE TITLE
Current NULL issues

### ISSUE THREAD

**Issue by EthanRPro** [libraryaddict/LibsDisguises#127]
currently having this issue in 1.8.5

[00:13:05] [Server thread/INFO]: EthanRAdmin issued server command: /d blaze
[00:13:05] [Server thread/INFO]: java.lang.NullPointerException
[00:13:05] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.createDisguise(Disguise.java:91)
[00:13:05] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:28)
[00:13:05] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.BaseDisguiseCommand.parseDisguise(BaseDisguiseCommand.java:400)
[00:13:05] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:27)
[00:13:05] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:13:05] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:13:05] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[00:13:05] [Server thread/INFO]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:13:05] [Server thread/INFO]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[00:13:05] [Server thread/INFO]: 	at java.lang.Thread.run(Unknown Source)
[00:13:05] [Server thread/INFO]: java.lang.NullPointerException
[00:13:05] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.BaseDisguiseCommand.parseDisguise(BaseDisguiseCommand.java:498)
[00:13:05] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:27)
[00:13:05] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:13:05] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:13:05] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[00:13:05] [Server thread/INFO]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:13:05] [Server thread/INFO]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[00:13:05] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[00:13:05] [Server thread/INFO]: 	at java.lang.Thread.run(Unknown Source)

**Comment by libraryaddict** [comment]
1.8 is no longer supported
