### ISSUE TITLE
error - PlayerJoinEvent - spigot 1.9.4

### ISSUE THREAD

**Issue by mat41997** [libraryaddict/LibsDisguises#131]
logs
http://hastebin.com/modulaxifi.avrasm

**Comment by mibby** [comment]
@libraryaddict Can also confirm. Assuming it is a protocollib issue?

LibsDisguise dev 20
ProtocolLib dev 275
Spigot 1.9.4

```
[17:31:50] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to LibsDisguises v9.0.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:333) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:159) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IllegalArgumentException: No suitable constructor could be found.
	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:179) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:923) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:463) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:109) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:157) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	... 14 more
Caused by: java.lang.RuntimeException: Detailed error com.comphenix.protocol.injector.BukkitUnwrapper@65ba5f86: com.comphenix.protocol.error.Report@18783b52
	at com.comphenix.protocol.error.RethrowErrorReporter.reportDetailed(RethrowErrorReporter.java:51) ~[?:?]
	at com.comphenix.protocol.error.RethrowErrorReporter.reportDetailed(RethrowErrorReporter.java:46) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.getFieldUnwrapper(BukkitUnwrapper.java:230) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.getSpecificUnwrapper(BukkitUnwrapper.java:186) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:109) ~[?:?]
	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:143) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:923) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:463) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:109) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:157) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	... 14 more
```

**Comment by mibby** [comment]
@libraryaddict https://github.com/libraryaddict/LibsDisguises/commit/e0293227ddd3417b6092c21f717515f4beadb97c Doesn't fix this error with getBedChunkPacket. Disabling the bed packet setting, error doesn't occur on login anymore.

```
[15:24:08] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to LibsDisguises v9.0.4-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-4af49dc-e22506f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4af49dc-e22506f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:333) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:159) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IllegalArgumentException: No suitable constructor could be found.
	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:179) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:923) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:492) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:130) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:199) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4af49dc-e22506f]
	... 14 more
Caused by: java.lang.RuntimeException: Detailed error com.comphenix.protocol.injector.BukkitUnwrapper@149fc4e7: com.comphenix.protocol.error.Report@69adc243
	at com.comphenix.protocol.error.RethrowErrorReporter.reportDetailed(RethrowErrorReporter.java:51) ~[?:?]
	at com.comphenix.protocol.error.RethrowErrorReporter.reportDetailed(RethrowErrorReporter.java:46) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.getFieldUnwrapper(BukkitUnwrapper.java:230) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.getSpecificUnwrapper(BukkitUnwrapper.java:186) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:109) ~[?:?]
	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:143) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:923) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:492) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:130) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:199) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4af49dc-e22506f]
	... 14 more
```

```
[15:27:07] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to LibsDisguises v9.0.4-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-4af49dc-e22506f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4af49dc-e22506f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-4af49dc-e22506f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IllegalArgumentException: No suitable constructor could be found.
	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:179) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:923) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:492) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:130) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onMove(DisguiseListener.java:219) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4af49dc-e22506f]
	... 15 more
Caused by: java.lang.RuntimeException: Detailed error com.comphenix.protocol.injector.BukkitUnwrapper@3881ff5a: com.comphenix.protocol.error.Report@32d9d7ce
	at com.comphenix.protocol.error.RethrowErrorReporter.reportDetailed(RethrowErrorReporter.java:51) ~[?:?]
	at com.comphenix.protocol.error.RethrowErrorReporter.reportDetailed(RethrowErrorReporter.java:46) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.getFieldUnwrapper(BukkitUnwrapper.java:230) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.getSpecificUnwrapper(BukkitUnwrapper.java:186) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:109) ~[?:?]
	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:143) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:923) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:492) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:130) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onMove(DisguiseListener.java:219) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4af49dc-e22506f]
	... 15 more
```

**Comment by andrewkm** [comment]
Can confirm.
http://pastie.org/private/wqfc6useazbu1ouespspw

**Comment by libraryaddict** [comment]
Please update
