### ISSUE TITLE
1.10 - Villager, Zombie and Skeleton Watchers call non-existent method getId()

### ISSUE THREAD

**Issue by eccentricdevotion** [libraryaddict/LibsDisguises#141]
Villager:
```
java.lang.NoSuchMethodError: org.bukkit.entity.Villager$Profession.getId()
at me.libraryaddict.disguise.disguisetypes.watchers.VillagerWatcher.setProfession(VillagerWatcher.java:25)
```
Zombie:
```
java.lang.NoSuchMethodError: org.bukkit.entity.Villager$Profession.getId()
at me.libraryaddict.disguise.disguisetypes.watchers.ZombieWatcher.setProfession(ZombieWatcher.java:80)
```
Skeleton:
```
java.lang.NoSuchMethodError: org.bukkit.entity.Skeleton$SkeletonType.getId()
at me.libraryaddict.disguise.disguisetypes.watchers.SkeletonWatcher.setType(SkeletonWatcher.java:17)
```

For Villagers and Zombies I have tried using the `public void setProfession(int id);` method, but that crashes my (un-modded) Minecraft client, crash log is viewable here: [crash log](https://dl.dropboxusercontent.com/u/53758864/crash-2016-06-09_22.43.20-client.txt)

SkeletonWatcher does not have a `public void setType(int id);` method to try...

Admittedly I am testing on CraftBukkit version git-Spigot-da278d1-5fc8091 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

LibsDisguises 9.0.6 build 36

ProtocolLib 4.0.2-SNAPSHOT build 293

**Comment by eccentricdevotion** [comment]
As of Bukkit 1.10 the deprecated `id` in the Profession and SkeletonType enums has been removed :(

I will now be patient and wait for LibsDisguises to be updated.
