### ISSUE TITLE
Error enabling: java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK

### ISSUE THREAD

**Issue by Stuperfied** [libraryaddict/LibsDisguises#148]
[21:24:57 INFO]: Starting minecraft server version 1.10

[21:24:57 INFO]: Loading properties

[21:24:57 INFO]: Default game type: SURVIVAL

[21:24:57 INFO]: This server is running CraftBukkit version git-Spigot-c55900f-9856d8a (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

[21:24:57 INFO]: Debug logging is disabled

[21:25:07 INFO]: [LibsDisguises] Enabling LibsDisguises v9.0.7

[21:25:07 INFO]: [LibsDisguises] Discovered MC version: v1_10_R1

[21:25:07 ERROR]: Error occurred while enabling LibsDisguises v9.0.7 (Is it up to date?)

java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK

```
at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerViewDisguises.<init>(PacketListenerViewDisguises.java:31) ~[?:?]

at me.libraryaddict.disguise.utilities.PacketsManager.init(PacketsManager.java:626) ~[?:?]

at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:69) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-c55900f-9856d8a]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-c55900f-9856d8a]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-c55900f-9856d8a]

at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-c55900f-9856d8a]

at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-c55900f-9856d8a]

at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-c55900f-9856d8a]

at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-c55900f-9856d8a]

at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-c55900f-9856d8a]

at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot.jar:git-Spigot-c55900f-9856d8a]

at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot.jar:git-Spigot-c55900f-9856d8a]

at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]
```

**Comment by oloflarsson** [comment]
Does this possibly have to do with what version of ProtocolLib you are using? I had this with ProtocolLib 3.8 but with ProtocolLib 4.0 this did not happen.

**Comment by Stuperfied** [comment]
There are users on the server currently but I will investigate and get back to you.

**Comment by Stuperfied** [comment]
Turns out you are correct, we were running an old version of ProtocolLib. I had downloaded it but forgot to upload it to the server. Thanks....
