### ISSUE TITLE
Stopped working wih MithicMobs + crash

### ISSUE THREAD

**Issue by Bodyash** [libraryaddict/LibsDisguises#150]
http://pastebin.com/wypCSc9v
http://pastebin.com/rwMnUTQk

Spigot 1.10.2
Latest protocolib + LD

**Comment by TheFluffyWalrus** [comment]
we are experience same issues except the most we have in logs is this
`30.06 21:14:52 [Server] ERROR java.lang.NullPointerException
30.06 21:14:52 [Server] ERROR java.lang.NullPointerException
30.06 21:14:52 [Server] ERROR java.lang.NullPointerException
30.06 21:14:52 [Server] ERROR java.lang.NullPointerException
30.06 21:14:52 [Server] ERROR java.lang.NullPointerException
30.06 21:14:52 [Server] ERROR java.lang.NullPointerException
30.06 21:14:52 [Disconnect] User Mayhem162 has disconnected, reason: Disconnected
30.06 21:14:52 [Disconnect] User LupoLight has disconnected, reason: Disconnected
30.06 21:14:52 [Disconnect] User FluffyTheWalrus has disconnected, reason: Disconnected`

**Comment by Bodyash** [comment]
![default](https://cloud.githubusercontent.com/assets/2454569/16686509/430ce46a-451b-11e6-9167-2687477275e8.PNG)

Zombie mob disguised with Player NickName. Not Working.

**Comment by Paulomart** [comment]
I would suggest enabling debug in the server's properties file.

**Comment by Bodyash** [comment]
How it can helps?

**Comment by Bodyash** [comment]
On mob spawn i get this error. In config mob must be disguised like Player. Its all.

**Comment by Paulomart** [comment]
Just for more info on the bug.

**Comment by Bodyash** [comment]
USING MythicMobs i can disguise mob like player and armour stand
http://mythicmobs.net/index.php?threads/player-disguise-doppleganger-skill.1967/#post-7031
http://mythicmobs.net/index.php?threads/disguise-zombie-like-armorstand-kick-nullpointer.1966/

Bu its working with older versions of MC, LibsDisguises and MM

**Comment by Bodyash** [comment]
[03:53:54] [Server thread/INFO]: [MythicMobs] Enabling MythicMobs v2.5.0
[03:53:54] [Server thread/INFO]: [MythicMobs] Loading MythicMobs for Bukkit v1_10_R1 (Minecraft 1.10)...
[03:53:54] [Server thread/INFO]: [MythicMobs] MythicMobs EffectLib Support has been enabled!
[03:53:54] [Server thread/INFO]: [MythicMobs] MythicMobs Lib's Disguises Support has been enabled!
[03:53:54] [Server thread/INFO]: [MythicMobs] MythicMobs Vault Support has been enabled!
[03:53:54] [Server thread/INFO]: [MythicMobs] MythicMobs WorldGuard Support has been enabled!
[03:53:54] [Server thread/WARN]: [MythicMobs] Failed to process Disguise: elder_guardian
[03:53:54] [Server thread/ERROR]: Error occurred while enabling MythicMobs v2.5.0 (Is it up to date?)
java.lang.NullPointerException
	at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.setSkin(PlayerDisguise.java:273) ~[?:?]
	at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.<init>(PlayerDisguise.java:40) ~[?:?]
	at net.elseland.xikage.MythicMobs.Compatibility.LibsDisguisesSupport.getDisguise(LibsDisguisesSupport.java:602) ~[?:?]
	at net.elseland.xikage.MythicMobs.Mobs.MythicMob.<init>(MythicMob.java:596) ~[?:?]
	at net.elseland.xikage.MythicMobs.IO.Load.LoadMobs.LoadAllMobs(LoadMobs.java:35) ~[?:?]
	at net.elseland.xikage.MythicMobs.IO.Load.Configuration.LoadAll(Configuration.java:145) ~[?:?]
	at net.elseland.xikage.MythicMobs.MythicMobs.onEnable(MythicMobs.java:166) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[Spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:417) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:382) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:337) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:540) [Spigot.jar:git-Spigot-7745d45-02d704b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]


Latest Version.
