### ISSUE TITLE
IllegalStateException: Cannot modify disguises on an async thread

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#159]
Paper dev 845 (Spigot 1.10.2)
LibsDisguise dev 56
ProtocolLib dev 320

```
[03:43:24] [Server thread/INFO]: player issued server command: /dis
[03:43:30] [Server thread/INFO]: player issued server command: /dis pig baby
[03:43:40] [Netty Epoll Server IO #0/WARN]: java.lang.IllegalStateException: Cannot modify disguises on an async thread
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.utilities.DisguiseUtilities.getPerverts(DisguiseUtilities.java:607)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.disguisetypes.FlagWatcher.sendData(FlagWatcher.java:456)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.disguisetypes.watchers.SheepWatcher.setColor(SheepWatcher.java:39)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.disguisetypes.watchers.SheepWatcher.setColor(SheepWatcher.java:31)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerClientInteract.onPacketReceiving(PacketListenerClientInteract.java:75)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at java.lang.Thread.run(Thread.java:745)
[03:43:40] [Netty Epoll Server IO #0/WARN]: java.lang.IllegalStateException: Cannot modify disguises on an async thread
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.utilities.DisguiseUtilities.getPerverts(DisguiseUtilities.java:607)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.disguisetypes.FlagWatcher.sendData(FlagWatcher.java:456)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.disguisetypes.watchers.SheepWatcher.setColor(SheepWatcher.java:39)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.disguisetypes.watchers.SheepWatcher.setColor(SheepWatcher.java:31)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerClientInteract.onPacketReceiving(PacketListenerClientInteract.java:75)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[03:43:40] [Netty Epoll Server IO #0/WARN]:     at java.lang.Thread.run(Thread.java:745)
```

**Comment by libraryaddict** [comment]
Is this still an issue

**Comment by mibby** [comment]
I have not seen the error in a while. Though it still may be an issue somewhere for however it modified disguises on an async thread.
