### ISSUE TITLE
NuSuchMethodException on SpigotMC 1.11

### ISSUE THREAD

**Issue by Rocologo** [libraryaddict/LibsDisguises#171]
[LibsDisguises] Discovered MC version: v1_11_R1
[10:11:45 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.EntityFishingHook.<init>(net.minecraft.server.v1_11_R1.World)
[10:11:45 WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[10:11:45 WARN]: 	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[10:11:45 WARN]: 	at me.libraryaddict.disguise.utilities.ReflectionManager.createEntityInstance(ReflectionManager.java:134)
[10:11:45 WARN]: 	at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:320)
[10:11:45 WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:116)
[10:11:45 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[10:11:45 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[10:11:45 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:11:45 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373)
[10:11:45 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323)
[10:11:45 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419)
[10:11:45 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380)
[10:11:45 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335)
[10:11:45 WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[10:11:45 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[10:11:45 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by mibby** [comment]
@libraryaddict 

LibsDisguise dev 61
PaperSpigot dev 928 (MC 1.11)
```
[21:39:55] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.0.9-SNAPSHOT
[21:39:55] [Server thread/INFO]: [LibsDisguises] Discovered MC version: v1_11_R1
[21:39:55] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.EntityFishingHook.<init>(net.minecraft.server.v1_11_R1.World)
[21:39:55] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Unknown Source)
[21:39:55] [Server thread/WARN]: 	at java.lang.Class.getDeclaredConstructor(Unknown Source)
[21:39:55] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.ReflectionManager.createEntityInstance(ReflectionManager.java:135)
[21:39:55] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:320)
[21:39:55] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:116)
[21:39:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[21:39:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[21:39:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[21:39:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377)
[21:39:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327)
[21:39:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:433)
[21:39:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:394)
[21:39:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:332)
[21:39:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276)
[21:39:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599)
[21:39:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:39:55] [Server thread/WARN]: [LibsDisguises] Entity not found! (FishingHook)
[21:39:55] [Server thread/WARN]: Error finding the FlagType for SHULKER! Index 15 can't be found!
[21:39:55] [Server thread/WARN]: Value is 10 (class java.lang.Byte) (class net.minecraft.server.v1_11_R1.EntityShulker) & ShulkerWatcher
[21:39:55] [Server thread/WARN]: Lib's Disguises will continue to load, but this will not work properly!
```

**Comment by libraryaddict** [comment]
Will be fixed later
