### ISSUE TITLE
Disguising Mobs as Players Crashes the Server

### ISSUE THREAD

**Issue by PeteyYT** [libraryaddict/LibsDisguises#186]
Hello,

I have a 1.8 Spigot server with ProtocolLib 4.2.0 and Lib's Disguises 8.6.7. Long story short, when I use the /disradius command to disguise, say, a zombie, I get this disconnect message:

"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1)"

Meanwhile, I get this message in the server console at the time of disconnect:
[18:43:39 INFO]: PeteyYT issued server command: /disradius 5 player Barbequeque
[18:43:39 INFO]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.PacketPlayOutPlayerInfo$EnumPlayerInfoAction
[18:43:39 INFO]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[18:43:39 INFO]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[18:43:39 INFO]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:43:39 INFO]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:43:39 INFO]:        at java.lang.Class.forName0(Native Method)
[18:43:39 INFO]:        at java.lang.Class.forName(Class.java:264)
[18:43:39 INFO]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[18:43:39 INFO]:        at java.lang.Thread.run(Thread.java:745)
[18:43:39 ERROR]: java.lang.NullPointerException
[18:43:39 ERROR]: java.lang.NullPointerException
[18:43:40 INFO]: PeteyYT left the game.

However, this function works fine on my other server with the same ProtocolLib and Lib's Disguises versions,  but with a 1.8.8 Spigot build (instead of a 1.8 Spigot build).

Is there a fix?

**Comment by libraryaddict** [comment]
Old versions are not supported, all old bugs were fixed in new versions.
