### ISSUE TITLE
Command Blocks can't use /disradius

### ISSUE THREAD

**Issue by Xeyler** [libraryaddict/LibsDisguises#192]
Here's the error from the console:

`[10:44:56 WARN]: CommandBlock at (-657,72,419) failed to handle command
org.bukkit.command.CommandException: Unhandled exception executing command 'disradius' in plugin LibsDisguises v9.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.CommandBlockListenerAbstract.executeCommand(CommandBlockListenerAbstract.java:232) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.CommandBlockListenerAbstract.executeSafely(CommandBlockListenerAbstract.java:139) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:104) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.BlockCommand.b(BlockCommand.java:76) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:722) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:250) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:790) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.command.CraftBlockCommandSender cannot be cast to org.bukkit.entity.Player
        at me.libraryaddict.disguise.commands.DisguiseRadiusCommand.onCommand(DisguiseRadiusCommand.java:155) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
        ... 12 more
`

The culprit:

Class DisguiseRadiusCommand.java
Line 155

CommandSender is cast to a Player. It would be best to instead get the location of the CommandSender regardless of whether it's a Player or a Command Block.

**Comment by libraryaddict** [comment]
Fixed
