### ISSUE TITLE
libdisguise version 8.6.7 minecraft  server version 1.8

### ISSUE THREAD

**Issue by shadowcaptain21** [libraryaddict/LibsDisguises#201]
hey im using correct protocolib and im using via versions when i disguise the world is bug i cant see anything its just all white and i get hits message on the console:
![2017-03-07_12 56 19](https://cloud.githubusercontent.com/assets/25735355/23642485/0235b036-02b0-11e7-86e6-a9e598be71b3.png)
 java.lang.reflect.InvocationTargetException
[05:46:13 INFO]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:46:13 INFO]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[05:46:13 INFO]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:46:13 INFO]:        at java.lang.reflect.Method.invoke(Method.java:498)
[05:46:13 INFO]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:760)
[05:46:13 INFO]:        at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:471)
[05:46:13 INFO]:        at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:375)
[05:46:13 INFO]:        at be.isach.ultracosmetics.UltraPlayer.clear(UltraPlayer.java:376)
[05:46:13 INFO]:        at be.isach.ultracosmetics.run.InvalidWorldManager.run(InvalidWorldManager.java:27)
[05:46:13 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[05:46:13 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[05:46:13 INFO]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[05:46:13 INFO]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[05:46:13 INFO]:        at java.lang.Thread.run(Thread.java:745)
[05:46:13 INFO]: Caused by: java.lang.IllegalStateException: Asynchronous player tracker clear!
[05:46:13 INFO]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[05:46:13 INFO]:        at net.minecraft.server.v1_8_R3.EntityTrackerEntry.clear(EntityTrackerEntry.java:544)
[05:46:13 INFO]:        ... 14 more

**Comment by shadowcaptain21** [comment]
and pls do support 1.8 version some plugins is on 1.8 that need lib disguise to work pls ._. or if your really cant just fix this bug thank you

**Comment by libraryaddict** [comment]
Old versions of Lib's Disguises are not supported, its why new versions are released.

**Comment by shadowcaptain21** [comment]
I said just fix It I understand u can't add support old version but pls fix it
