### ISSUE TITLE
Error changing skin

### ISSUE THREAD

**Issue by Wolf2323** [libraryaddict/LibsDisguises#211]
error when changing skin in MyticMobs with LibsDisguises

`
[22:35:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mm' in plugin MythicMobs v4.0.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at io.lumine.xikage.mythicmobs.commands.eggs.GiveCommand.onCommand(GiveCommand.java:54) ~[?:?]
	at io.lumine.xikage.mythicmobs.util.commands.Command.onCommand(Command.java:68) ~[?:?]
	at io.lumine.xikage.mythicmobs.util.commands.Command.onCommand(Command.java:59) ~[?:?]
	at io.lumine.xikage.mythicmobs.util.commands.Command.onCommand(Command.java:59) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	... 15 more
[22:35:39] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AssertionError: TRAP
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_11_R1.ItemStack.F(ItemStack.java:94) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.ItemStack.setCount(ItemStack.java:822) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:403) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:966) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[spigot-1.11.2.jar:git-Spigot-28463de-a2af8f0]
	... 5 more
`

**Comment by libraryaddict** [comment]
Sorry but I can't see how this is a bug caused by Lib's Disguises
