### ISSUE TITLE
NPE while disabling LibsDisguises v9.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by eccentricdevotion** [libraryaddict/LibsDisguises#223]
`[13:26:27 ERROR]: Error occurred while disabling LibsDisguises v9.4.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.saveDisguises(DisguiseUtilities.java:87) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onDisable(LibsDisguises.java:123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[craftbukkit.jar:git-Bukkit-bb4ae3b]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:353) [craftbukkit.jar:git-Bukkit-bb4ae3b]`

**Comment by libraryaddict** [comment]
Happened because you deleted plugin folder while plugin running

**Comment by libraryaddict** [comment]
Fixed next time I push
