### ISSUE TITLE
Incompatibility with latest ProtocolLib builds

### ISSUE THREAD

**Issue by sgdc3** [libraryaddict/LibsDisguises#251]
Server version: paperspigot 1.11.2
ProtocolLib version: build 378 (http://ci.dmulloy2.net/job/ProtocolLib/)
LibsDisguises version: tried both 9.4.0 and latest dev build

StackTrace:

```
[12:17:40 WARN]: java.lang.IllegalArgumentException: Unable to find Serializer for {}! Are you running the latest version of ProtocolLib?
[12:17:40 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.createDataWatcherItem(ReflectionManager.java:867)
[12:17:40 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.createWatchable(ReflectionManager.java:886)
[12:17:40 WARN]:        at me.libraryaddict.disguise.disguisetypes.FlagWatcher.convert(FlagWatcher.java:109)
[12:17:40 WARN]:        at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:912)
[12:17:40 WARN]:        at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:57)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[12:17:40 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:198)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1109)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:317)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:323)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.d(EntityTrackerEntry.java:290)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:232)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.EntityTracker.updatePlayers(EntityTracker.java:182)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:923)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[12:17:40 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[12:17:40 WARN]:        at java.lang.Thread.run(Thread.java:745)

```

**Comment by libraryaddict** [comment]
Mind trying the latest build? Error should change a little at least.

**Comment by sgdc3** [comment]
> and latest dev

**Comment by sgdc3** [comment]
ah ok, you want to see the stacktrace with latest dev build, i'll try to send it to you asap, but as i remember it was almost identical

**Comment by sgdc3** [comment]
wait, i'm almost sure i copied the stacktrace while i had both protocollib and libsdisguises at the latest dev build

**Comment by libraryaddict** [comment]
There's a new build of Lib's Disguises, 159. You are using 158

**Comment by sgdc3** [comment]
uh, i missed that, let me check

**Comment by sgdc3** [comment]
New stacktrace:

```
[15:31:19 WARN]: java.lang.IllegalArgumentException: Unable to find Serializer for {}net.minecraft.server.v1_11_R1.NBTTagCompound! Are you running the latest version of ProtocolLib?
[15:31:19 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.createDataWatcherItem(ReflectionManager.java:869)
[15:31:19 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.createWatchable(ReflectionManager.java:887)
[15:31:19 WARN]:        at me.libraryaddict.disguise.disguisetypes.FlagWatcher.convert(FlagWatcher.java:109)
[15:31:19 WARN]:        at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:912)
[15:31:19 WARN]:        at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:57)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[15:31:19 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:198)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1109)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:317)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:323)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.d(EntityTrackerEntry.java:290)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:232)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.EntityTracker.updatePlayers(EntityTracker.java:182)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:923)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[15:31:19 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[15:31:19 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by libraryaddict** [comment]
Should be fixed in latest build

**Comment by sgdc3** [comment]
I'll let you know

**Comment by sgdc3** [comment]
@libraryaddict Still not working:
```
[17:05:27 WARN]: java.lang.IllegalArgumentException: handle cannot be NULL.
[17:05:27 WARN]:        at com.comphenix.protocol.wrappers.AbstractWrapper.setHandle(AbstractWrapper.java:29)
[17:05:27 WARN]:        at com.comphenix.protocol.wrappers.WrappedWatchableObject.<init>(WrappedWatchableObject.java:53)
[17:05:27 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.createWatchable(ReflectionManager.java:890)
[17:05:27 WARN]:        at me.libraryaddict.disguise.disguisetypes.FlagWatcher.convert(FlagWatcher.java:109)
[17:05:27 WARN]:        at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:912)
[17:05:27 WARN]:        at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:57)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[17:05:27 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:198)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1109)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:317)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:323)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.d(EntityTrackerEntry.java:290)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:232)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.EntityTracker.updatePlayers(EntityTracker.java:182)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:923)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[17:05:27 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[17:05:27 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by libraryaddict** [comment]
Fixed in latest dev build. Again.

**Comment by sgdc3** [comment]
Still happening, same log

**Comment by libraryaddict** [comment]
How embarrassing.. Definitely fixed now.

**Comment by sgdc3** [comment]
i'll test it asap

**Comment by sgdc3** [comment]
Seems fixed, thank you.
