### ISSUE TITLE
1.13.1 error with libsdisguises prem

### ISSUE THREAD

**Issue by malonnnn** [libraryaddict/LibsDisguises#303]
Edit:
You can close this thread, it works fine in spigot 1.13.1 but not paper 1.13.1 and i know you dont support anything other than spigot. sry

> [17:49:17] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.6.0-SNAPSHOT
> [17:49:17] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_13_R2
> [17:49:17] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar, premium enabled!
> [17:49:17] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
> [17:49:17] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [17:49:17] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [17:49:17] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [17:49:17] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [17:49:17] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.ReflectionManager.getParticleType(ReflectionManager.java:845)
> [17:49:17] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.ReflectionManager.convertInvalidMeta(ReflectionManager.java:837)
> [17:49:17] [Server thread/WARN]: at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:519)
> [17:49:17] [Server thread/WARN]: at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:62)
> [17:49:17] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [17:49:17] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
> [17:49:17] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [17:49:17] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434)
> [17:49:17] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348)
> [17:49:17] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
> [17:49:17] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:576)
> [17:49:17] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:433)
> [17:49:17] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:305)
> [17:49:17] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784)
> [17:49:17] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [17:49:17] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Particle SPELL_MOB requires data, null provided
> [17:49:17] [Server thread/WARN]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
> [17:49:17] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftParticle.toNMS(CraftParticle.java:124)
> [17:49:17] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftParticle.toNMS(CraftParticle.java:109)
> [17:49:17] [Server thread/WARN]: ... 19 more
> [17:49:17] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v9.6.0-SNAPSHOT (Is it up to date?)
> java.lang.NullPointerException: null
> at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:522) ~[?:?]
> at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:62) ~[?:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.1.jar:git-Paper-206]
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.1.jar:git-Paper-206]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-206]
> at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[patched_1.13.1.jar:git-Paper-206]
> at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[patched_1.13.1.jar:git-Paper-206]
> at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-206]
> at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:576) ~[patched_1.13.1.jar:git-Paper-206]
> at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:433) ~[patched_1.13.1.jar:git-Paper-206]
> at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.1.jar:git-Paper-206]
> at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784) ~[patched_1.13.1.jar:git-Paper-206]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
> [17:49:17] [Server thread/INFO]: [LibsDisguises] Disabling LibsDisguises v9.6.0-SNAPSHOT

**Comment by malonnnn** [comment]
Yup! it works!

Thank you!
