### ISSUE TITLE
Join Error

### ISSUE THREAD

**Issue by FrankHeijden** [libraryaddict/LibsDisguises#315]
```
18.11 13:09:04 [Server] ERROR Could not pass event PlayerJoinEvent to LibsDisguises v9.6.0-SNAPSHOT
18.11 13:09:04 [Server] INFO org.bukkit.event.EventException: null
18.11 13:09:04 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:170) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:66) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:253) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO at java.lang.Thread.run(Thread.java:844) [?:?]
18.11 13:09:04 [Server] INFO Caused by: java.lang.NullPointerException
18.11 13:09:04 [Server] INFO at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:307) ~[?:?]
18.11 13:09:04 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor327.execute(Unknown Source) ~[?:?]
18.11 13:09:04 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-451]
18.11 13:09:04 [Server] INFO ... 14 more
```

Displayed on join on 1.13.2

**Comment by libraryaddict** [comment]
Which snapshot are you using?

**Comment by FrankHeijden** [comment]
b239

**Comment by libraryaddict** [comment]
Can you try the latest build
