### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Nerovey** [libraryaddict/LibsDisguises#316]
```
[20-11-2018 00:48:13] Task #105 for RealVillagerTowns v1.2 generated an exception
[20-11-2018 00:48:13] java.lang.NoClassDefFoundError: Could not initialize class me.libraryaddict.disguise.disguisetypes.DisguiseType
[20-11-2018 00:48:13] at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.<init>(PlayerDisguise.java:33) ~[?:?]
[20-11-2018 00:48:13] at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.<init>(PlayerDisguise.java:45) ~[?:?]
[20-11-2018 00:48:13] at io.hotmail.com.jacob_vejvoda.RVT.RVT.disguise(RVT.java:2108) ~[?:?]
[20-11-2018 00:48:13] at io.hotmail.com.jacob_vejvoda.RVT.RVT$10.run(RVT.java:2072) ~[?:?]
[20-11-2018 00:48:13] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 00:48:13] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 00:48:13] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 00:48:13] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 00:48:13] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 00:48:13] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 00:48:13] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

I'm trying to use this plugin with RVT, I have everything updated to 1.12.2 yet the skins of the villagers aren't working and its from an issue from this plugin, it loops with this error while the server is running but I haven't found any fixes online after searching, anyone know whats going on? I'm on spigot 1.12.2.

When using any of the libdisguise commands it comes back with 'an internal error occurred while attempting to perform this command'

**Comment by libraryaddict** [comment]
Can you provide the startup log?

**Comment by Nerovey** [comment]
`[20-11-2018 21:49:23] Disabling LibsDisguises v9.6.0-SNAPSHOT
[20-11-2018 21:49:23] No updates found!
[20-11-2018 21:49:23] Enabling RealVillagerTowns v1.2
[20-11-2018 21:49:23] Error occurred while enabling RealVillagerTowns v1.2 (Is it up to date?)
[20-11-2018 21:49:23] java.lang.ExceptionInInitializerError: null
[20-11-2018 21:49:23] at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.<init>(PlayerDisguise.java:33) ~[?:?]
[20-11-2018 21:49:23] at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.<init>(PlayerDisguise.java:45) ~[?:?]
[20-11-2018 21:49:23] at io.hotmail.com.jacob_vejvoda.RVT.RVT.disguise(RVT.java:2108) ~[?:?]
[20-11-2018 21:49:23] at io.hotmail.com.jacob_vejvoda.RVT.RVT.makeVillagers(RVT.java:368) ~[?:?]
[20-11-2018 21:49:23] at io.hotmail.com.jacob_vejvoda.RVT.RVT.onEnable(RVT.java:117) ~[?:?]
[20-11-2018 21:49:23] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[20-11-2018 21:49:23] Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.COD
[20-11-2018 21:49:23] at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_181]
[20-11-2018 21:49:23] at org.bukkit.entity.EntityType.valueOf(EntityType.java:1) ~[spigot.jar:git-Spigot-eadd615-4509a14]
[20-11-2018 21:49:23] at me.libraryadd`

I get this error while the server is starting up as well as this one later on:

`org.bukkit.command.CommandException: Cannot execute command 'disguise' in plugin LibsDisguises v9.6.0-SNAPSHOT - plugin is disabled`

**Comment by libraryaddict** [comment]
You've downloaded the latest snapshot.

https://ci.md-5.net/job/LibsDisguises/207/

Is the last 1.12 release
