### ISSUE TITLE
/dis or any command about LibsDisguises doesn't work

### ISSUE THREAD

**Issue by DevilishDante** [libraryaddict/LibsDisguises#323]
Hi, i test you're lastest update and when i do a command there are nothing, literraly nothing not event an error in the console

version of spigot : 
[10:42:44 INFO]: This server is running CraftBukkit version git-Spigot-fe3ab0d-162bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[10:42:44 INFO]: You are 153 version(s) behind

and i cannot update my spigot :c any suggestion? ,thans for reading me
PS: i don't have any config file exept disguises.yml u.u

**Comment by libraryaddict** [comment]
https://github.com/libraryaddict/LibsDisguises/blob/master/src/main/resources/config.yml#L19

Check your Libs Disguises config
Also any errors on Libs Disguises start?

**Comment by DevilishDante** [comment]
i don't have any config.yml i try delete folder's plugin :o

**Comment by libraryaddict** [comment]
Can you provide your startup log?

**Comment by DevilishDante** [comment]
hi there are this in console:
`[13:09:57] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.7.1
[13:09:57] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_13_R1
[13:09:57] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #247
[13:09:57] [Server thread/WARN]: java.lang.NoSuchFieldException: BIOME
[13:09:57] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[13:09:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:515)
[13:09:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.init(DisguiseUtilities.java:877)
[13:09:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:58)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[13:09:57] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:09:57] [Server thread/WARN]: java.lang.NullPointerException
[13:09:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.init(DisguiseUtilities.java:878)
[13:09:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:58)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[13:09:57] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:09:57] [Server thread/WARN]: java.lang.NoSuchFieldException: ENTITY_TYPE
[13:09:57] [Server thread/WARN]: 	at java.lang.Class.getField(Class.java:1703)
[13:09:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.ReflectionManager.getEntityType(ReflectionManager.java:990)
[13:09:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:538)
[13:09:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:60)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[13:09:57] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:09:57] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v9.7.1 (Is it up to date?)
java.lang.IllegalStateException: Failed to find EntityType for EntityAreaEffectCloud
	at me.libraryaddict.disguise.utilities.ReflectionManager.getEntityType(ReflectionManager.java:999) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:538) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:60) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`
But only at startup and there is a lastest.log
https://pastebin.com/xxAGxwgz with pastebin link :o

**Comment by DevilishDante** [comment]
Hi, there are not a previous version work with 1.13? :o

**Comment by libraryaddict** [comment]
Weird, I didn't see your message.

https://ci.md-5.net/job/LibsDisguises/219/

But, this is a premium-only build and 100% not recommended. I don't believe you should be using any version but the latest for 1.13, which is built for 1.13.2 and you have reported issues when using on 1.13.0.

I recommend updating your server to 1.13.2

**Comment by DevilishDante** [comment]
Hello, thanks for u support i don't know it was for 1.13.2 but my new project will be in 1.13.2 👍 
And thanks for this, i'll use it temporarily  and sorry for the not real issues ><

PS: sorry for my english x)
