### ISSUE TITLE
NPE in PlayerTeleportEvent

### ISSUE THREAD

**Issue by Silthus** [libraryaddict/LibsDisguises#324]
On server startup LibsDisguises throws a lot of the same NPE error:

```
[16:38:33] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to LibsDisguises v9.7.1-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-483]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-483]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-483]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-483]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:723) ~[patched_1.13.2.jar:git-Paper-483]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:334) ~[patched_1.13.2.jar:git-Paper-483]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:224) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:135) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:280) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:33) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:177) ~[?:?]
        at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:120) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-483]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-483]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-483]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-483]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-483]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-483]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at com.comphenix.protocol.injector.netty.ChannelInjector.findChannelHandler(ChannelInjector.java:843) ~[?:?]
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:745) ~[?:?]
        at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:204) ~[?:?]
        at me.libraryaddict.disguise.DisguiseListener.onTeleport(DisguiseListener.java:629) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-483]
        ... 18 more
```

These errors get fired when spawning NPCs. The NPCs do not appear. Maybe there is a MetaKey Check for NPCs missing?

I am using the PremiumJar from the Spigot ressource download section. Server Information:
```
This server is running Paper version git-Paper-483 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:38:11] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v9.7.1-SNAPSHOT
[16:38:11] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.7.1-SNAPSHOT
[16:38:11] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_13_R2
[16:38:11] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #249
[16:38:11] [Server thread/WARN]: java.lang.ClassNotFoundException: me.libraryaddict.disguise.utilities.LibsPremium
[16:38:11] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[16:38:11] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:38:11] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:38:11] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.LibsPremium.check(LibsPremium.java:37)
[16:38:11] [Server thread/WARN]:        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:48)
[16:38:11] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[16:38:11] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[16:38:11] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:38:11] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[16:38:11] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[16:38:11] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[16:38:11] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
[16:38:11] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[16:38:11] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[16:38:11] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[16:38:11] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:38:12] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[16:38:12] [Server thread/INFO]: [LibsDisguises] Loaded 1 custom disguise
[16:38:12] [Server thread/WARN]: [LibsDisguises] Your config is missing 6 options! Please consider regenerating your config!
```

**Comment by libraryaddict** [comment]
The second error is weird, looks like you have an invalid jar in the plugin folder.

As for the first error, are you using their latest version?

**Comment by libraryaddict** [comment]
@Silthus are you using paper as well?

**Comment by Silthus** [comment]
Yes I am using paper spigot
libraryaddict <notifications@github.com> schrieb am Fr. 21. Dez. 2018 um
11:06:

**Comment by libraryaddict** [comment]
I edited my message, the email didn't reflect this.

> Ah, my mistake. You included it in the error.
> 
> Is it possible to test if the error occurs on normal spigot? Chances are, paper is doing something and I don't know what.

**Comment by Silthus** [comment]
I just tested it with spigot and the errors are gone. I also fixed the startup error by downloading the latest jar again.

Seems to be a paper problem.

**Comment by libraryaddict** [comment]
Which protocol lib are you using?

**Comment by Silthus** [comment]
> Which protocol lib are you using?

I am using ProtocolLib 4.4.0

**Comment by libraryaddict** [comment]
Reported fixed in latest build of Citizens
