### ISSUE TITLE
Error ! :D

### ISSUE THREAD

**Issue by TheIntelloBox** [libraryaddict/LibsDisguises#328]
Hey ! 🗡 

[18:13:13] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #247
[18:13:13] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v9.7.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/WrappedParticle
	at me.libraryaddict.disguise.disguisetypes.MetaIndex.<clinit>(MetaIndex.java:43) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:557) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:60) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.wrappers.WrappedParticle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
	... 14 more

Thanks for fixing it ! :D 
TheIntelloBox. :D

**Comment by libraryaddict** [comment]
Please use the latest stable build of ProtocolLib

http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/
