### ISSUE TITLE
bug load paperspigot 1.13.2

### ISSUE THREAD

**Issue by ProDash1998** [libraryaddict/LibsDisguises#340]
[16:59:01 ERROR]: Could not load 'plugins\LibsDisguises-9.7.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ProtocolLib
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) ~[spigot.jar:git-Paper-513]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[spigot.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[spigot.jar:git-Paper-513]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[spigot.jar:git-Paper-513]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by libraryaddict** [comment]
Please use https://www.spigotmc.org/resources/protocollib.1997/
