### ISSUE TITLE
libsDisguises error

### ISSUE THREAD

**Issue by geumu** [libraryaddict/LibsDisguises#350]
Bukkit: Paperspigot 1.13.2
Plugin Version: LibsDisguises v9.8.0
Note: I installed openj9.

[16:42:04] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[16:42:04] [Server thread/WARN]: java.lang.IllegalArgumentException: Unable to find findStatistic in net.minecraft.server.v1_13_R2.StatisticList
[16:42:04] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:280)
[16:42:04] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.WrappedStatistic.<clinit>(WrappedStatistic.java:24)
[16:42:04] [Server thread/WARN]: 	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
[16:42:04] [Server thread/WARN]: 	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:843)
[16:42:04] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693)
[16:42:04] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012)
[16:42:04] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031)
[16:42:04] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62)
[16:42:04] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45)
[16:42:04] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:902)
[16:42:04] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.init(DisguiseUtilities.java:961)
[16:42:04] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:66)
[16:42:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[16:42:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[16:42:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[16:42:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[16:42:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[16:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[16:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[16:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[16:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[16:42:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[16:42:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:813)

**Comment by libraryaddict** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/556#issuecomment-456212127
