### ISSUE TITLE
BUG ERROR SELECT MOB

### ISSUE THREAD

**Issue by andfont** [libraryaddict/LibsDisguises#360]
version LibsDisguises
[01:34:23] [Server thread/INFO]: LibsDisguises version 9.8.2-SNAPSHOT
MC-SPigot 1.14.1
when we want to select any mob gives error:
[01:32:45] [Server thread/INFO]: andfont issued server command: /disguise Bat
[01:32:45] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'disguise' in plugin LibsDisguises v9.8.2-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot.jar:git-Spigot-8043ebc-02b466c]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at me.libraryaddict.disguise.utilities.DisguiseUtilities.removeSelfDisguise(DisguiseUtilities.java:1239) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.Disguise.startDisguise(Disguise.java:821) ~[?:?]
        at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:73) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
        ... 17 more
[01:34:04] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 10612ms or 212 ticks behind

**Comment by libraryaddict** [comment]
Using latest version of ProtocolLib?

This is a bug in their plugin.

**Comment by andfont** [comment]
???? for version 1.14 you have to use the latest version of the protocollib as indicated on its website:
https://www.spigotmc.org/resources/protocollib.1997/
Could you please adapt your plugin to the version of protocollib for 14? as it seems they tell me that you have not adapted your plugin to your protocollib for version 1.14.1

**Comment by andfont** [comment]
I have also used the protocollib 440 and it happens exactly the same problem, it is clear that it is a problem of your plugin not to close the case please!

**Comment by libraryaddict** [comment]
I don't call org/apache/commons/lang3/Validate

ProtocolLib does.

ProtocolLib dev did not reply to you.
