### ISSUE TITLE
NullPointerException on disguise/undisguise with ViewSelfDisguises set to true.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#375]
Paper dev 122 (Spigot 1.14.3)
LibsDisguise dev 293
ProtocolLib Gradle dev 9

Error on disguise/undisguise when ViewSelfDisguises is set to true.
```
[22:05:35] [Server thread/INFO]: player issued server command: /dis panda
[22:05:35] [Server thread/WARN]: java.lang.NullPointerException
[22:05:35] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:1554)
[22:05:35] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1727)
[22:05:35] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:832)
[22:05:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[22:05:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[22:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132)
[22:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
[22:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
[22:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[22:05:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:05:39] [Server thread/INFO]: player issued server command: /undis
[22:05:39] [Server thread/WARN]: java.lang.NullPointerException
[22:05:39] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.removeSelfDisguise(DisguiseUtilities.java:1266)
[22:05:39] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:539)
[22:05:39] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:480)
[22:05:39] [Server thread/WARN]: 	at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:408)
[22:05:39] [Server thread/WARN]: 	at me.libraryaddict.disguise.commands.UndisguiseCommand.onCommand(UndisguiseCommand.java:22)
[22:05:39] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:05:39] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:05:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:738)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978)
[22:05:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912)
[22:05:39] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by libraryaddict** [comment]
Can you provide your startup log

**Comment by mibby** [comment]
Compiled as of commit https://github.com/libraryaddict/LibsDisguises/commit/fd2f7e4fbc394486775d00552f98fd7d14279ef8 for dev testing.

Reduced start-up log. No initialization errors. Disguises work fine otherwise when ViewSelfDisguises is disabled.
```
[16:09:20] [Server thread/INFO]: Starting minecraft server version 1.14.3
[16:09:20] [Server thread/INFO]: Loading properties
[16:09:20] [Server thread/INFO]: This server is running Paper version git-Paper-122 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
[16:09:20] [Server thread/INFO]: Server Ping Player Sample Count: 12
[16:09:20] [Server thread/INFO]: Using 4 threads for Netty based IO
[16:09:20] [Server thread/INFO]: Debug logging is disabled
[16:09:20] [Server thread/INFO]: Default game type: SURVIVAL
[16:09:20] [Server thread/INFO]: Generating keypair
[16:09:27] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.5.0-SNAPSHOT
[16:09:28] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.14.3) has not yet been tested! Proceed with caution.
[16:09:29] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v9.8.2-SNAPSHOT
[16:09:33] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.5.0-SNAPSHOT
[16:09:33] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[16:09:42] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.8.2-SNAPSHOT
[16:09:42] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_14_R1
[16:09:42] [Server thread/INFO]: [LibsDisguises] Jenkins Build: unknown
[16:09:42] [Server thread/INFO]: [LibsDisguises] Build Date: 01/07/2019 22:45
[16:09:43] [Server thread/INFO]: [LibsDisguises] Loaded 0 custom disguises
[16:09:57] [Server thread/INFO]: Done (21.559s)! For help, type "help"
[16:09:57] [Server thread/INFO]: Using epoll channel type
[16:09:57] [Server thread/INFO]: Timings Reset
```

Did however come across this error in my logs as well.
```
[17:26:07] [Server thread/ERROR]: [LibsDisguises] Unhandled exception occured in onSyncPacket() for LibsDisguises
java.lang.NullPointerException: null
	at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:50) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:640) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.access$1000(AsyncListenerHandler.java:48) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$5.run(AsyncListenerHandler.java:441) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-122]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[17:26:07] [Server thread/ERROR]: [LibsDisguises] Unhandled exception occured in onSyncPacket() for LibsDisguises
java.lang.NullPointerException: null
	at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:50) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:640) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.access$1000(AsyncListenerHandler.java:48) ~[?:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$5.run(AsyncListenerHandler.java:441) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-122]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[17:26:07] [Craft Scheduler Thread - 842/WARN]: java.util.ConcurrentModificationException
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at java.util.ArrayList$Itr.next(ArrayList.java:859)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:140)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:144)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:107)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.mineacademy.chatcontrol.final. .CoM9.const(SourceFile:1300)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.mineacademy.chatcontrol.final. .CoM6.save(SourceFile:395)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.mineacademy.chatcontrol.final. .G.const(SourceFile:94)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.mineacademy.chatcontrol.final. .w.const(SourceFile:126)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[17:26:07] [Craft Scheduler Thread - 842/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by libraryaddict** [comment]
It appears you're using a custom compiled version of Lib's Disguises, as such I cannot give any support.

**Comment by mibby** [comment]
Well, it is your fork with just the version check commented out for 1.14 testing... But if you don't want valid issues reported to you, so be it. 🤷‍♂

**Comment by libraryaddict** [comment]
That's a great way to say you didn't buy it..

**Comment by mibby** [comment]
"You can still download it for free! Read the plugin's description! You'll need to be logged in!"

If you didn't want to provide a free alternative for players and developers to use LibsDisguise, especially for early 1.14 testing and informing of existing problems, then don't.

**Comment by libraryaddict** [comment]
You are looking for an excuse to complain, I'm sorry that you are offended by the beta version of software that has known crashing issues not being released to the general public.

And that the same developer is unwilling to debug someone else's code.

Despite your complaints the free version shall remain free of charge.

**Comment by mibby** [comment]
I'm not looking for an excuse to complain. I'm replying to your retort that no support will be given because I compiled your code. If you don't want someone to help debug and report issues, fine.
