### ISSUE TITLE
NoSuchMethodException on Startup

### ISSUE THREAD

**Issue by thenameisKO** [libraryaddict/LibsDisguises#383]
Server Version: Spigot 1.14.4
ProtocolLib Version: 4.5.0-SNAPSHOT
Libs Disguises Version: 9.8.2 (Premium)
Using latest dev build from Jenkins (Build #294)

This issue prevents use of LibsDisguises entirely as running the /disguise command afterward results in nothing happening (no errors thrown other than the following error at startup).

`[00:06:45] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.8.2
[00:06:46] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.EntityCow.<init>(net.minecraft.server.v1_14_R1.World)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.createEntityInstance(ReflectionManager.java:158)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:41)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[00:06:46] [Server thread/WARN]: java.lang.NullPointerException
[00:06:46] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:06:46] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:06:46] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:55)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[00:06:46] [Server thread/WARN]: java.lang.NoSuchFieldException: tracker
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:515)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:528)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:72)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[00:06:46] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.EntityTracker
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:315)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsClass(ReflectionManager.java:466)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:528)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:74)
[00:06:46] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[00:06:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[00:06:46] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776)
[00:06:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[00:06:46] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v9.8.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:515) ~[?:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:528) ~[?:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:74) ~[?:?]
	... 10 more`

**Comment by libraryaddict** [comment]
Can you provide startup log?

**Comment by thenameisKO** [comment]
The given error was from the startup log; if you need a full log including other plugins, I would prefer to privately send it to you (such as via Spigot) if that isn't too much trouble.
