### ISSUE TITLE
Error in latest dev build

### ISSUE THREAD

**Issue by axemwa** [libraryaddict/LibsDisguises#389]
[04:46:40 ERROR]: Error occurred while enabling LibsDisguises v9.8.2-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:56) ~[?:?]
        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-641]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-641]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-641]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-641]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-641]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-641]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.CAT
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_221]
        at org.bukkit.entity.EntityType.valueOf(EntityType.java:20) ~[patched_1.13.2.jar:git-Paper-641]
        at me.libraryaddict.disguise.disguisetypes.DisguiseType.<init>(DisguiseType.java:256) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.DisguiseType.<clinit>(DisguiseType.java:21) ~[?:?]
        ... 13 mor

**Comment by libraryaddict** [comment]
The latest dev builds are provided for 1.14, the 1.13 builds are linked on the plugin page and named as such.

**Comment by axemwa** [comment]
whoops soz my bad I haven't visited the plugin page in quite some time
