### ISSUE TITLE
Console error when transforming into non-living entities is set to false in the config

### ISSUE THREAD

**Issue by malonnnn** [libraryaddict/LibsDisguises#392]
```[17:48:32 ERROR]: null                                                                                                        
org.bukkit.command.CommandException: Unhandled exception executing command 'dis' in plugin LibsDisguises v9.8.2-SNAPSHOT      
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.4.jar:git-Paper-172]                
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-1$
2]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-$
aper-172]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[pat$
hed_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-P$
per-172]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper$
172]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-P$
per-172]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Pape$
-172]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Pa$
er-172]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Pape$
-172]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.RuntimeException: Cannot disguise a living entity with a misc disguise. Reenable MiscDisguisesForLiving $
n the config to do this
        at me.libraryaddict.disguise.disguisetypes.Disguise.setEntity(Disguise.java:607) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.MiscDisguise.setEntity(MiscDisguise.java:166) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.MiscDisguise.setEntity(MiscDisguise.java:15) ~[?:?]
        at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:64) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-172]
        ... 17 more```

**Comment by libraryaddict** [comment]
I'm assuming the problem is that it should tell you this in the command, not in console?

Something I should've caught :P
