### ISSUE TITLE
Random error message on player join

### ISSUE THREAD

**Issue by SirLemonade** [libraryaddict/LibsDisguises#397]
Hello,
A player joined and there was an error message when they did, of libsdisguises.
Error: https://pastebin.com/ehA3VVk4

Doesn't seem very significant. Still reporting it.

**Comment by libraryaddict** [comment]
Do you happen to use saved disguises?

**Comment by SirLemonade** [comment]
Yes i use saved disguises
The player that joined was an admin and they mightve been disguised when they left.

**Comment by malonnnn** [comment]
I can confirm this issue, I also used save disguises

```[15:19:39 ERROR]: Could not pass event PlayerJoinEvent to LibsDisguises v9.8.2-SNAPSHOT
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to java.util.Optional
        at me.libraryaddict.disguise.disguisetypes.FlagWatcher.getCustomName(FlagWatcher.java:208) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.FlagWatcher.hasCustomName(FlagWatcher.java:263) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.Disguise.setupWatcher(Disguise.java:715) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.Disguise.setEntity(Disguise.java:615) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.setEntity(PlayerDisguise.java:185) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.setEntity(PlayerDisguise.java:25) ~[?:?]
        at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:302) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor298.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-187]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-187]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-187]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1232) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-187]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]```
