### ISSUE TITLE
Paper support

### ISSUE THREAD

**Issue by erDUKE21** [libraryaddict/LibsDisguises#410]
>.... [19:52:06 ERROR]: Could not load 'plugins/LibsDisguises-9.8.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Operand stack underflow
Exception Details:
Location:
me/libraryaddict/disguise/LibsDisguises.getInstance()Lme/libraryaddict/disguise/LibsDisguises; @0: areturn
Reason:
Attempt to pop empty stack.
Current Frame:
bci: @0
flags: { }
locals: { }
stack: { }
Bytecode:
0x0000000: b0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-226]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-226]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.VerifyError: Operand stack underflow
Exception Details:
Location:
me/libraryaddict/disguise/LibsDisguises.getInstance()Lme/libraryaddict/disguise/LibsDisguises; @0: areturn
Reason:
Attempt to pop empty stack.
Current Frame:
bci: @0
flags: { }
locals: { }
stack: { }
Bytecode:
0x0000000: b0
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-226]
... 6 more

**Comment by libraryaddict** [comment]
Could you tell me what build you're trying to run, if you own the plugin, and if you downloaded it from jenkins or compiled from scratch.

Using the latest version of Paper, the plugin loads with no errors.

**Comment by erDUKE21** [comment]
Hi I'm using the 9.8.4
