### ISSUE TITLE
NoClassDefFoundError: org/apache/commons/lang3/Validate

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#412]
LibsDisguises dev 333
Purpur dev 333 (PaperSpigot dev 234)
ProtocolLib dev 432

```
[03:28:41] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.8.5-SNAPSHOT
[03:28:41] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_14_R1
[03:28:41] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #333
[03:28:41] [Server thread/INFO]: [LibsDisguises] Build Date: 11/12/2019 08:46
[03:28:41] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v9.8.4, build #311, created 05/11/2019 04:28)
[03:28:41] [Server thread/INFO]: [LibsDisguises] Registered to: 819 (18)
[03:28:41] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[03:28:41] [Server thread/INFO]: [LibsDisguises] Loaded 0 custom disguises
```

```
[03:47:55] [Server thread/INFO]: player issued server command: /disguise Mushroom_Cow baby
[03:47:55] [Server thread/WARN]: [LibsDisguises] Task #33605 for LibsDisguises v9.8.5-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
	at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:1562) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1729) ~[?:?]
	at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:836) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[paperclip.jar:git-Purpur-333]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[paperclip.jar:git-Purpur-333]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1178) ~[paperclip.jar:git-Purpur-333]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:426) ~[paperclip.jar:git-Purpur-333]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1105) ~[paperclip.jar:git-Purpur-333]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:932) ~[paperclip.jar:git-Purpur-333]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.Validate
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[paperclip.jar:git-Purpur-333]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[paperclip.jar:git-Purpur-333]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 15 more
```

https://paste.ubuntu.com/p/bNKDJpCrMx/

**Comment by libraryaddict** [comment]
http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/

**Comment by mibby** [comment]
I actually grabbed ProtocolLib from lucko's jenkins since that one failed.
https://ci.lucko.me/job/ProtocolLib/

But it compiled the same source version commit that 432 is.

**Comment by libraryaddict** [comment]
The gradle version I linked doesn't need apache3. And its what everyone else uses.
