### ISSUE TITLE
LibsDisguises error on startup

### ISSUE THREAD

**Issue by x1p** [libraryaddict/LibsDisguises#415]
LibsDisguises v9.8.9 on Paper 1.14.4
```
[14:35:52] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v9.8.9 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.<clinit>(ReflectionManager.java:49) ~[?:?]
at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:47) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-235]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.BEE
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_212]
at org.bukkit.entity.EntityType.valueOf(EntityType.java:23) ~[patched_1.14.4.jar:git-Paper-235]
at me.libraryaddict.disguise.disguisetypes.DisguiseType.<init>(DisguiseType.java:259) ~[?:?]
at me.libraryaddict.disguise.disguisetypes.DisguiseType.<clinit>(DisguiseType.java:18) ~[?:?]
... 11 more
```

**Comment by SoSeDiK** [comment]
Isn't it for 1.15?
There's a link for the latest 1.14.4 build on the plugin's page at spigotmc.

**Comment by x1p** [comment]
You're right. Damn I thought it was backwards compatible
