### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by TheCleverGamer** [libraryaddict/LibsDisguises#419]
[15:54:06 ERROR]: [LibsDisguises] Unhandled exception occured in onPacketSending(PacketEvent) for LibsDisguises
java.lang.IllegalArgumentException: entityID cannot be negative
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:205) ~[ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:643) ~[ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:628) ~[ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib%204.5.0.jar:4.5.0]
        at me.libraryaddict.disguise.utilities.PacketsManager$5.onPacketSending(PacketsManager.java:1230) ~[LibsDisguises%208.6.7.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib%204.5.0.jar:4.5.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib%204.5.0.jar:4.5.0]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:280) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:176) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:177) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[15:54:06 ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayOutEntity$PacketPlayOutRelEntityMove@192ec6e7[
    a=-1
    b=0
    c=0
    d=0
    e=0
    f=0
    g=false
    h=false
  ]

After upload LibsDisguises and latest ProtocolLib I get this error

**Comment by libraryaddict** [comment]
https://www.spigotmc.org/resources/protocollib.1997/download?version=165553
