### ISSUE TITLE
java.lang.IllegalArgumentException: No serializer found for class com.comphenix.protocol.wrappers.nbt.WrappedCompound

### ISSUE THREAD

**Issue by mckite** [libraryaddict/LibsDisguises#420]
Describe the bug
java.lang.IllegalArgumentException: No serializer found for class com.comphenix.protocol.wrappers.nbt.WrappedCompound

To Reproduce
I don't know

Expected behavior
No console error

Version Info

paperspigot 1518 (1.12.2)

LibsDisguises 9.5.2
ProtocolLib : 4.4.0 (Other version get error for another, more freq.)

https://pastebin.com/72fWjZBG

Provide your ProtocolLib install info with /protocol dump through pastebin.
[19:54:01] [Server thread/WARN]: java.lang.IllegalArgumentException: No serializer found for class com.comphenix.protocol.wrappers.nbt.WrappedCompound
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:940)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.createDataWatcher(PacketsManager.java:504)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.constructSpawnPackets(PacketsManager.java:366)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:918)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:57)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:369)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:516)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:119)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:104)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:30)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.b(World.java:1219)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1207)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1212)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1145)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1115)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:729)
[19:54:01] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:655)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.now(Teleport.java:127)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.teleport(Teleport.java:198)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.back(Teleport.java:264)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.commands.Commandback.run(Commandback.java:25)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Essentials.onCommand(Essentials.java:430)
[19:54:01] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:54:01] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[19:54:01] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[19:54:01] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:54:01] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:54:01] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)
[19:54:01] [Server thread/WARN]: java.lang.IllegalArgumentException: No serializer found for class com.comphenix.protocol.wrappers.nbt.WrappedCompound
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:940)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.createDataWatcher(PacketsManager.java:504)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.constructSpawnPackets(PacketsManager.java:366)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:918)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:57)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:369)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:516)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:119)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:104)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:30)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.b(World.java:1219)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1207)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1212)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1145)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1115)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:729)
[19:54:01] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:655)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.now(Teleport.java:127)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.teleport(Teleport.java:198)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.back(Teleport.java:264)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.commands.Commandback.run(Commandback.java:25)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Essentials.onCommand(Essentials.java:430)
[19:54:01] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:54:01] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[19:54:01] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[19:54:01] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:54:01] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:54:01] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)
[19:54:01] [Server thread/WARN]: java.lang.IllegalArgumentException: No serializer found for class com.comphenix.protocol.wrappers.nbt.WrappedCompound
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:940)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.createDataWatcher(PacketsManager.java:504)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.constructSpawnPackets(PacketsManager.java:366)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:918)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:57)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:369)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:516)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:119)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:104)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:30)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.b(World.java:1219)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1207)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1212)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1145)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1115)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:729)
[19:54:01] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:655)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.now(Teleport.java:127)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.teleport(Teleport.java:198)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.back(Teleport.java:264)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.commands.Commandback.run(Commandback.java:25)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Essentials.onCommand(Essentials.java:430)
[19:54:01] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:54:01] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[19:54:01] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[19:54:01] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:54:01] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:54:01] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)
[19:54:01] [Server thread/WARN]: java.lang.IllegalArgumentException: No serializer found for class com.comphenix.protocol.wrappers.nbt.WrappedCompound
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:940)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.createDataWatcher(PacketsManager.java:504)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.constructSpawnPackets(PacketsManager.java:366)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:918)
[19:54:01] [Server thread/WARN]: at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:57)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:54:01] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:369)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:516)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:119)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:104)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:30)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.b(World.java:1219)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1207)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1212)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1145)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1115)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:729)
[19:54:01] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:655)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.now(Teleport.java:127)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.teleport(Teleport.java:198)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Teleport.back(Teleport.java:264)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.commands.Commandback.run(Commandback.java:25)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517)
[19:54:01] [Server thread/WARN]: at com.earth2me.essentials.Essentials.onCommand(Essentials.java:430)
[19:54:01] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:54:01] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[19:54:01] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[19:54:01] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:54:01] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:54:01] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:54:01] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by libraryaddict** [comment]
https://www.spigotmc.org/resources/protocollib.1997/download?version=165553

If you get random error on startup with getWrappedStatisticConverter (Ctrl-F it) mentioned

Your version of Java was likely updated, please downgrade.

**Comment by mckite** [comment]
But, using ProtocolLib 4.3.0 causes errror for other plugins,
other plugins are perferctly work on ProtocoLib 4.4.0

**Comment by libraryaddict** [comment]
I don't recall what this error is caused by, however I don't support older versions of Lib's Disguises.

Is there a particular reason you can't update to 1.15?

**Comment by mckite** [comment]
Yes, 
1. 1.15 has more lag than 1.12.2 (Even, highest speed of sing core thread, it will be limited low acceptable online players)
2. incompatible plugins in 1.15
3. Too much changes between 1.13
4. Lack of those version's demand in my player's country
