### ISSUE TITLE
v10.0.7 NoClassDefFoundError

### ISSUE THREAD

**Issue by N0tMyFaultOG** [libraryaddict/LibsDisguises#464]
I'm getting the following error on startup
```
[09:51:21] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.7
[09:51:21] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_12_R1
[09:51:21] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #552
[09:51:21] [Server thread/INFO]: [LibsDisguises] Build Date: 01/05/2020 02:58
[09:51:21] [Server thread/INFO]: [LibsDisguises] Registered to: 586081 (28)
[09:51:21] [Server thread/INFO]: [LibsDisguises] Ew, LibsDisguises-10.0.5.jar is so old
[09:51:21] [Server thread/INFO]: [LibsDisguises] Copied LibsDisguises-10.0.7-Premium.jar to the plugin folder! You can use dev builds with premium enabled!
[09:51:21] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[09:51:21] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[09:51:21] [Server thread/INFO]: [LibsDisguises] Loaded 1 custom disguise
[09:51:21] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v10.0.7 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/org/apache/commons/io/FileUtils
	at me.libraryaddict.disguise.DisguiseConfig.saveDefaultConfig(DisguiseConfig.java:531) ~[?:?]
	at me.libraryaddict.disguise.DisguiseConfig.loadConfig(DisguiseConfig.java:769) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.org.apache.commons.io.FileUtils
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 14 more
[09:51:21] [Server thread/INFO]: [LibsDisguises] Disabling LibsDisguises v10.0.7
```
I updated from 10.0.5 to 10.0.7. Currently tested on paper 1.12 (git-Paper-1618 (MC: 1.12.2))

Edit: Included everything regarding LibsDisguises.

**Comment by libraryaddict** [comment]
Looks like I missed that, I'll have to fix it tomorrow but for now I believe regenerating your config will correct the issue.

**Comment by libraryaddict** [comment]
Actually I might have a build ready in about 5 minutes

**Comment by libraryaddict** [comment]
https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/artifact/target/LibsDisguises.jar
