### ISSUE TITLE
Could not pass event PlayerTeleportEvent to LibsDisguises

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#481]
LibsDisguise dev 620
Tuinity dev 117 (Paper Fork / Spigot 1.15.2)

Was disguised as a ``falling_block stone_pressure_plate``, then teleport to a player in a different world.

```
[15:55:01] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to LibsDisguises v10.0.12-SNAPSHOT
java.lang.NullPointerException: null
	at me.libraryaddict.disguise.utilities.listeners.DisguiseListener.onTeleport(DisguiseListener.java:592) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor195.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:775) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportPaper.lambda$teleportAsync$0(AsyncTeleportPaper.java:16) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1143) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1248) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1262) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:780) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1155) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1131) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Tuinity-"7c03cbe"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

Config
https://paste.ubuntu.com/p/cBv6nqZRrB/

```
[15:40:26] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.12-SNAPSHOT
[15:40:26] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_15_R1
[15:40:26] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #620
[15:40:26] [Server thread/INFO]: [LibsDisguises] Build Date: 15/06/2020 14:32
[15:40:26] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v10.0.12, build #607, created 24/05/2020 04:53)
[15:40:26] [Server thread/INFO]: [LibsDisguises] Registered to: 819 (18)
[15:40:26] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[15:40:27] [Server thread/INFO]: [LibsDisguises] Loaded 0 custom disguises
[15:40:27] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[15:40:27] [Server thread/INFO]: [LibsDisguises] The author sees Metrics disabled, the author is sad
```

**Comment by libraryaddict** [comment]
Try latest build
