### ISSUE TITLE
WARN: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by SoSeDiK** [libraryaddict/LibsDisguises#490]
Code used for disguise:
```
MobDisguise mobDisguise = new MobDisguise(DisguiseType.ARMOR_STAND);
mobDisguise.setViewSelfDisguise(true);
mobDisguise.setEntity(player);

LivingWatcher watcher = mobDisguise.getWatcher();
watcher.getEquipment().setItemInOffHand(new ItemStack(Material.DIAMOND_SHOVEL));
watcher.getEquipment().setItemInMainHand(new ItemStack(Material.DIAMOND_SWORD));

mobDisguise.startDisguise();
```
Warning:
```
[18:21:14 WARN]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
[18:21:14 WARN]:        at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:755)
[18:21:14 WARN]:        at java.base/java.util.ArrayList.add(ArrayList.java:480)
[18:21:14 WARN]:        at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerEquipment.handleNew(PacketHandlerEquipment.java:76)
[18:21:14 WARN]:        at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerEquipment.handle(PacketHandlerEquipment.java:44)
[18:21:14 WARN]:        at me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:69)
[18:21:14 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfPacket(DisguiseUtilities.java:2149)
[18:21:14 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:2039)
[18:21:14 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:2212)
[18:21:14 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:1168)
[18:21:14 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[18:21:14 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[18:21:14 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
[18:21:14 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[18:21:14 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[18:21:14 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[18:21:14 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[18:21:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
```
Versions:
`git-Paper-34 (MC: 1.16.1)`, `ProtocolLib v4.6.0-SNAPSHOT-b467`, `LibsDisguises v10.0.13-SNAPSHOT build 645`

**Comment by libraryaddict** [comment]
Forgot to mention fixed in latest builds
