### ISSUE TITLE
Player's skin keeps disappear and error message

### ISSUE THREAD

**Issue by mm2015** [libraryaddict/LibsDisguises#51]
I make all zombie disguise as a player, but the skin keep disappear and showing the original steve skin.

And these error message pops up.

[20:29:15] [Craft Scheduler Thread - 5/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@ce0d851[id=7017dedf-edf7-4afe-b46c-5d38444e2a11,name=djd,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[spigot-1.7.10-R0.1-20140911a.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [spigot-1.7.10-R0.1-20140911a.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
	at me.libraryaddict.disguise.utilities.ReflectionManager.getSkullBlob(ReflectionManager.java:509) [LibsDisguises-b359.jar:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.lookupGameProfile(DisguiseUtilities.java:592) [LibsDisguises-b359.jar:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities$3.run(DisguiseUtilities.java:522) [LibsDisguises-b359.jar:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.7.10-R0.1-20140911a.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.7.10-R0.1-20140911a.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.7.0_67]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.7.0_67]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]

**Comment by NavidK0** [comment]
Irrelevant issue.
