### ISSUE TITLE
[Console Error]

### ISSUE THREAD

**Issue by VeteranDrenor** [libraryaddict/LibsDisguises#515]
Hello, i have an error when I spawn a mobs with libdisguise :

[14:36:50 ERROR]: [MythicMobs] [SCHEDULER] Exception thrown whilst executing task
[14:36:50 WARN]: java.lang.NoSuchMethodError: me.libraryaddict.disguise.disguisetypes.Disguise.setShowName(Z)Lme/libraryaddict/disguise/disguisetypes/Disguise;
[14:36:50 WARN]:        at io.lumine.xikage.mythicmobs.compatibility.LibsDisguisesSupport.getDisguise(LibsDisguisesSupport.java:936)
[14:36:50 WARN]:        at io.lumine.xikage.mythicmobs.compatibility.LibsDisguisesSupport.setDisguise(LibsDisguisesSupport.java:192)
[14:36:50 WARN]:        at io.lumine.xikage.mythicmobs.skills.mechanics.DisguiseMechanic.cast(DisguiseMechanic.java:26)
[14:36:50 WARN]:        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.executeNoTargetSkill(SkillMechanic.java:462)
[14:36:50 WARN]:        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeSkills$4(SkillMechanic.java:428)
[14:36:50 WARN]:        at io.lumine.xikage.mythicmobs.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[14:36:50 WARN]:        at io.lumine.xikage.mythicmobs.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[14:36:50 WARN]:        at io.lumine.xikage.mythicmobs.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[14:36:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[14:36:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[14:36:50 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[14:36:50 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[14:36:50 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[14:36:50 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[14:36:50 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[14:36:50 WARN]:        at java.lang.Thread.run(Unknown Source)

Can you help me to resolve this problem ?
Thanks you :)

**Comment by libraryaddict** [comment]
I believe this was addressed in discord, the solution was an invalid MM command.
