### ISSUE TITLE
PaperMC 1.16.3 Internal server error

### ISSUE THREAD

**Issue by kingvonx** [libraryaddict/LibsDisguises#516]
[15:55:36 INFO]: UUID of player KingVonx is a7df5435-c7d1-317f-be67-1cbfcb89b93c
[15:55:36 WARN]: Failed to handle packet for /127.0.0.1:53412
net.minecraft.server.v1_16_R2.ReportedException: Sending packet
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1638) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.PlayerConnection.sendPacket(PlayerConnection.java:1603) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.PlayerList.a(PlayerList.java:197) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.LoginListener.c(LoginListener.java:167) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.LoginListener.tick(LoginListener.java:65) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:380) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalStateException: Cannot use reflection.
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:30) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:353) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R2.NetworkManager.b(NetworkManager.java:288) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.NetworkManager.dispatchPacket(NetworkManager.java:244) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.NetworkManager.sendPacket(NetworkManager.java:220) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1630) ~[patched_1.16.3.jar:git-Paper-220]
        ... 12 more
Caused by: java.lang.IllegalAccessException: Can not set final net.minecraft.server.v1_16_R2.Packet field net.minecraft.server.v1_16_R2.NetworkManager$$Lambda$4282/0x000000080180ed28.arg$4 to net.minecraft.server.v1_16_R2.PacketPlayOutEntityStatus
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:793) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:26) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:353) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R2.NetworkManager.b(NetworkManager.java:288) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.NetworkManager.dispatchPacket(NetworkManager.java:244) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.NetworkManager.sendPacket(NetworkManager.java:220) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1630) ~[patched_1.16.3.jar:git-Paper-220]
        ... 12 more
[15:55:36 INFO]: KingVonx lost connection: Internal server error

**Comment by libraryaddict** [comment]
I believe this is an issue caused by ProtocolLib and the latest version of Java not being compatible

**Comment by libraryaddict** [comment]
Solution is to downgrade java or wait for ProtocolLib to fix this.
