### ISSUE TITLE
Incompatible with ViaBackwards

### ISSUE THREAD

**Issue by Yertled** [libraryaddict/LibsDisguises#523]
I had an issue with certain disguises with ViaBackwards.
When someone disguised as a drowned or other certain disguises, they would not be able to reconnect to the server, and was permanently locked out until we removed disguises from the server.

[06:08:09] [Server thread/INFO]: Riverforest15 issued server command: /disguise Drowned
[06:08:09] [Netty Server IO #2/WARN]: [ViaBackwards] Unable to handle metadata Metadata{id=13, metaType=Float, value=0.0} for entity type DROWNED
[06:08:09] [Netty Server IO #2/WARN]: [ViaBackwards] Full metadata list: Metadata{id=0, metaType=Byte, value=64}
Metadata{id=1, metaType=VarInt, value=300}
Metadata{id=2, metaType=OptChat, value=null}
Metadata{id=3, metaType=Boolean, value=false}
Metadata{id=4, metaType=Boolean, value=false}
Metadata{id=5, metaType=Boolean, value=false}
Metadata{id=6, metaType=Pose, value=0}
Metadata{id=7, metaType=Byte, value=0}
Metadata{id=8, metaType=Float, value=20.0}
Metadata{id=9, metaType=VarInt, value=0}
Metadata{id=10, metaType=Boolean, value=false}
Metadata{id=11, metaType=VarInt, value=0}
Metadata{id=12, metaType=OptPosition, value=null}
Metadata{id=13, metaType=Float, value=0.0}
Metadata{id=14, metaType=VarInt, value=2041}
Metadata{id=15, metaType=Byte, value=127}
Metadata{id=16, metaType=Byte, value=1}
Metadata{id=17, metaType=NBTTag, value=CompoundTag { {} }}
Metadata{id=18, metaType=NBTTag, value=CompoundTag { {} }}
[06:08:09] [Netty Server IO #2/WARN]: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Byte
[06:08:09] [Netty Server IO #2/WARN]: 	at nl.matsv.viabackwards.protocol.protocol1_13_2to1_14.packets.EntityPackets1_14.lambda$registerRewrites$7(EntityPackets1_14.java:442)
[06:08:09] [Netty Server IO #2/WARN]: 	at nl.matsv.viabackwards.api.rewriters.EntityRewriterBase.handleMeta(EntityRewriterBase.java:163)
[06:08:09] [Netty Server IO #2/WARN]: 	at nl.matsv.viabackwards.api.rewriters.LegacyEntityRewriter$3.lambda$registerMap$0(LegacyEntityRewriter.java:89)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[06:08:09] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[06:08:09] [Netty Server IO #2/WARN]: 	at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
[06:08:09] [Netty Server IO #2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06:08:09] [Netty Server IO #2/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[06:08:09] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:477)
[06:08:09] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[06:08:09] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[06:08:09] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[06:08:09] [Netty Server IO #2/WARN]: 	at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:78)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.izzel.taboolib.module.packet.channel.ChannelExecutor$ChannelHandler.write(ChannelExecutor.java:62)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[06:08:09] [Netty Server IO #2/WARN]: 	at me.MrGraycat.eGlow.Util.Packets.PacketInjector$1.write(PacketInjector.java:74)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[06:08:09] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[06:08:09] [Netty Server IO #2/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:300)
[06:08:09] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[06:08:09] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[06:08:09] [Netty Server IO #2/WARN]: 	at java.lang.Thread.run(Unknown Source)
[06:08:09] [Netty Server IO #2/WARN]: [ViaBackwards] Unable to handle metadata Metadata{id=13, metaType=Float, value=0.0} for entity type DROWNED
[06:08:09] [Netty Server IO #2/WARN]: [ViaBackwards] Full metadata list: Metadata{id=0, metaType=Byte, value=64}

**Comment by libraryaddict** [comment]
Just checked through my code, it looks like an issue in ViaBackwards as I shouldn't be sending metadata 13 with float.
