### ISSUE TITLE
java.lang.IllegalArgumentException: java.lang.ClassCastException disguising arrows (projectiles) as fallingblock cobweb

### ISSUE THREAD

**Issue by totemo** [libraryaddict/LibsDisguises#526]
I'm seeing this exception in the latest snapshot (build #809) running on PaperSpigot git-Paper-249 (MC: 1.16.3) when disguising arrows as `fallingblock cobweb` using `DisguiseAPI.disguiseToAll(Entity,Disguise)`:

```
[22:59:31] [Server thread/WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@643d421a
[22:59:31] [Server thread/WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[22:59:31] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:59:31] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:59:31] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.hasInvul(ReflectionManager.java:261)
[22:59:31] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:97)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[22:59:31] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.NetworkManager.b(NetworkManager.java:288)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.NetworkManager.dispatchPacket(NetworkManager.java:244)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.NetworkManager.sendPacket(NetworkManager.java:220)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1640)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.sendPacket(PlayerConnection.java:1613)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.PlayerList.sendPacketNearby(PlayerList.java:1137)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.playSound(WorldServer.java:1550)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.Entity.playSound(Entity.java:1018)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.EntityArrow.a(EntityArrow.java:408)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.IProjectile.a(IProjectile.java:127)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.EntityArrow.tick(EntityArrow.java:176)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.EntityTippedArrow.tick(EntityTippedArrow.java:92)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:841)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:884)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:526)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[22:59:31] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[22:59:31] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

This used to work flawlessly in Minecraft 1.15.2. The arrows are correctly disguised as cobwebs, but console is spammed with exceptions.

**Comment by libraryaddict** [comment]
Fixed in latest build

**Comment by totemo** [comment]
I can confirm that is working well. Thank you for this and #525.
