### ISSUE TITLE
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R2.entity.CraftZombie cannot be cast to org.bukkit.entity.Player

### ISSUE THREAD

**Issue by hkkongou** [libraryaddict/LibsDisguises#528]
[22:37:56 WARN]: [LibsDisguises] Task #4975305 for LibsDisguises v10.0.20 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R2.entity.CraftZombie cannot be cast to org.bukkit.entity.Player
	at me.libraryaddict.disguise.disguisetypes.Disguise$1.run(Disguise.java:506) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Tuinity-"576e2cc"]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Tuinity-"576e2cc"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1354) ~[patched_1.16.3.jar:git-Tuinity-"576e2cc"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372) ~[patched_1.16.3.jar:git-Tuinity-"576e2cc"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267) ~[patched_1.16.3.jar:git-Tuinity-"576e2cc"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Tuinity-"576e2cc"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Tuinity-"576e2cc"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

error log
https://drive.google.com/file/d/1VXT3M_WAD4R_UmCex_AIk9-BoU_Z5cSU/view?usp=sharing

mob used for mythicmobs disguises

LibsDisguises 10.0.20 Premium 
Tuinity 1.16.3 576e2cc / papermc 1.16.3 #253

**Comment by libraryaddict** [comment]
I believe this should've been fixed in the latest dev build, can you check? Use /ld update dev

**Comment by hkkongou** [comment]
um..
![image](https://user-images.githubusercontent.com/61608872/102716375-7cf98180-4316-11eb-9b5e-ebc34ba325a4.png)

**Comment by hkkongou** [comment]
i try try
![image](https://user-images.githubusercontent.com/61608872/102716382-8be03400-4316-11eb-8466-1cd809d8b9ce.png)

**Comment by hkkongou** [comment]
no, the error still happening

**Comment by hkkongou** [comment]
this error is not appearing any more , thx!
but another error come when first player login server.

![image](https://user-images.githubusercontent.com/61608872/102716465-188af200-4317-11eb-86e7-5721b1e7543f.png)
the server log is here:

https://drive.google.com/file/d/1Q3Dyf1g2QI_0EzftQvnxq1ey_OUlDVU6/view?usp=sharing
