### ISSUE TITLE
NoSuchMethod error when disguising a wolf

### ISSUE THREAD

**Issue by unon1100** [libraryaddict/LibsDisguises#53]
When disguising a wolf as a sheep with the following code
```
public static void sheepify(Entity e) {
        MobDisguise sheep = new MobDisguise(DisguiseType.SHEEP, false, true);
        SheepWatcher wt = (SheepWatcher) sheep.getWatcher();
        wt.setAdult();
        wt.setCustomName("" + ChatColor.GOLD + LootFactory.getRandomElementFromList(Utils.names));
        wt.setCustomNameVisible(true);
        int i = new Random().nextInt(17);
        if(i == 16) wt.setSheared(true);
        else wt.setColor((Arrays.asList(AnimalColor.values())).get(i));
        sheep.setWatcher(wt);
        DisguiseAPI.disguiseToAll(e, sheep);
    }
```
I get an error on the line
`sheep.setWatcher(wt);`

Stacktrace:
```
[16:05:07 ERROR]: Could not pass event PlayerInteractEvent to PZSG v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:636) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NoSuchMethodError: me.libraryaddict.disguise.disguisetypes.MobDisguise.setWatcher(Lme/libraryaddict/disguise/disguisetypes/FlagWatcher;)V
        at net.mcpz.sg.utils.data.DisguiseMob.sheepify(DisguiseMob.java:30) ~[?:?]
        at net.mcpz.sg.listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:207) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        ... 15 more
```

Version of the plugins: http://gyazo.com/ddd966919b317e4b0c46d80f285754cb

**Comment by NavidK0** [comment]
Resolved.
