### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by masterrip** [libraryaddict/LibsDisguises#533]
I need help I have a problem with the plug-in Lib's Disguises prem. on my server paper 1.15.2

Spam in a console with a heavy load on the processor. Spam occurs when a player dies and during teleportation.

[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
[22:33:48 WARN]:        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
[22:33:48 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158)
[22:33:48 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[22:33:48 WARN]:        at com.google.gson.Gson.getAdapter(Gson.java:423)
[22:33:48 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)

**Comment by libraryaddict** [comment]
Can you try the latest dev build
