### ISSUE TITLE
[Issue] Slime & Magma Cube disguises can be used to crash the clients of nearby players

### ISSUE THREAD

**Issue by WhatsTheBadNews** [libraryaddict/LibsDisguises#551]
I am having trouble reproducing this on my test server, but I know it can happen on my production server. I am hoping I can get this fixed or some advice if my server is configured incorrectly.

Basically, you use `/disguise Magma_Cube` or `/disguise Slime` a few times and it will crash the clients of nearby players. I can provide client log errors for said crashes. (From .minecraft/logs)

Example 1:
https://pastebin.com/TmYpq74M

Example 2:
https://pastebin.com/1cFtQmfz

Relevant Version Information:
Server: Tunity-192 Minecraft 1.16.5
LibsDisguises: 10.0.24-Premium
ProtocolLib: 498 (latest dev build)

I don't think the versions are super important though, as we have been having this issue reported for a while. I can provide any more relevant information if needed.

**Comment by libraryaddict** [comment]
Try the latest dev build

**Comment by WhatsTheBadNews** [comment]
Hello, I tried the dev build. I had a player that was still able to crash his friend by using `/disguise slime` 2 times.

Client log of the friend who crashed: https://pastebin.com/M2wPjasW

**Comment by resi23** [comment]
Why closed the problem persists. I have the same problem with the version built 2 minutes ago.

Server: Paper-740 (MC: 1.16.5)
LibsDisguises: v10.0.24-SNAPSHOT
ProtocolLib: 501 (latest dev build)

**Comment by libraryaddict** [comment]
Provide your latest.log please

**Comment by resi23** [comment]
Dont have any error from LibsDisguises only

```[09:32:47] [Server thread/INFO]: ResistantX issued server command: /d slime
[09:32:53] [Server thread/INFO]: ResistantX issued server command: /u
[09:32:53] [Server thread/ERROR]: Could not pass event UndisguiseEvent to eGlow v3.0.7
java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity me.libraryaddict.disguise.events.UndisguiseEvent.getEntity()'
	at me.MrGraycat.eGlow.Addon.Disguises.LibDisguiseAddon.onUnDisguise(LibDisguiseAddon.java:60) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor885.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-740]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-740]
	at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:683) ~[?:?]
	at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:663) ~[?:?]
	at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:446) ~[?:?]
	at me.libraryaddict.disguise.commands.undisguise.UndisguiseCommand.onCommand(UndisguiseCommand.java:30) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1265) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1258) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1219) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-740]
	at java.lang.Thread.run(Unknown Source) [?:?]```
	
Client log
```[09:33:51] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team '09NallaLeandraA'.
	at net.minecraft.class_269.method_1157(class_269.java:236) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2151) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34) ~[intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_2600$$Lambda$3785/366325940.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:191) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:153) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:130) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1015) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]```

**Comment by libraryaddict** [comment]
We are talking about clients crashing yes?
Because you just gave me a log where another plugin that isn't Lib's Disguises has an error.
I fail to see how its related.

**Comment by resi23** [comment]
I don't think it's related. I have no errors from Lib's Disguises in the Server.log. But the clients of the other players crash when I turn into a Slime or Magma Slime

**Comment by resi23** [comment]
same problem and nothing in server logfile
[10:30:01] [Server thread/INFO]: ResistantX issued server command: /d Slime
[10:30:21] [Server thread/INFO]: ResistantX issued server command: /u

**Comment by libraryaddict** [comment]
Use /ld logs and provide that.

Your issue is completely unrelated to this.

**Comment by resi23** [comment]
My log file: https://pastebin.com/n9X4MAFp, my combined config files: https://pastebin.com/vcA19mvN and my disguises file: https://pastebin.com/U0X39bLj

**Comment by libraryaddict** [comment]
Your problem starts with a pirated and custom build of lib's disguises and ends with another plugin entirely.

Please don't contact me again.
