### ISSUE TITLE
InaccessibleObjectException on startup with Java 16

### ISSUE THREAD

**Issue by Pugabyte** [libraryaddict/LibsDisguises#557]
```
[11:06:02] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.1-SNAPSHOT-b501
[11:06:03] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v10.0.24-SNAPSHOT
[11:06:03] [Server thread/WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @31ef2919
[11:06:03] [Server thread/WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[11:06:03] [Server thread/WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[11:06:03] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[11:06:03] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[11:06:03] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.reflection.asm.AsmDownloader.<init>(AsmDownloader.java:49)
[11:06:03] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.init(WatcherSanitizer.java:78)
[11:06:03] [Server thread/WARN]:        at me.libraryaddict.disguise.LibsDisguises.onLoad(LibsDisguises.java:108)
[11:06:03] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394)
[11:06:03] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252)
[11:06:03] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[11:06:03] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[11:06:03] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[11:06:03] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
[11:06:03] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.init(WatcherSanitizer.java:79)
[11:06:03] [Server thread/WARN]:        at me.libraryaddict.disguise.LibsDisguises.onLoad(LibsDisguises.java:108)
[11:06:03] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394)
[11:06:03] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252)
[11:06:03] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[11:06:03] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[11:06:03] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[11:06:03] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
[11:06:03] [Server thread/WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
[11:06:03] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182)
[11:06:03] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
[11:06:03] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[11:06:03] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[11:06:03] [Server thread/WARN]:        ... 7 more
[11:06:03] [Server thread/ERROR]: [LibsDisguises] Registered: []
```

Paper 1.16.5 #654 
Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9-Ubuntu-120.04) Host: Linux 5.4.0-29-generic (amd64)

**Comment by Dymeth** [comment]
> Latest dev builds should be compatible with Java 16

Cannot invoke "me.libraryaddict.disguise.utilities.reflection.NmsVersion.ordinal()" because the return value of "me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getVersion()" is null initializing LibsDisguises v10.0.12-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.libraryaddict.disguise.utilities.reflection.NmsVersion.ordinal()" because the return value of "me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getVersion()" is null
	at me.libraryaddict.disguise.utilities.reflection.NmsVersion.isSupported(NmsVersion.java:16) ~[?:?]
	at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.init(WatcherSanitizer.java:85) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onLoad(LibsDisguises.java:63) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:396) ~[patched_1.16.5.jar:git-Paper-693]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-693]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-693]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-693]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by libraryaddict** [comment]
The latest build should now fully support 16
