### ISSUE TITLE
No Such Field Exception Warning

### ISSUE THREAD

**Issue by LaurenceBarnes** [libraryaddict/LibsDisguises#558]
During the startup of the server, I get this warning. The plugin seems to be loaded and it seems to work though. Tried with both the latest Full release and the latest Snapshot.

Purpur-1116. It started happening after either Purpur-1111 or Purpur-1109, but I also updated other plugins together with updating Purpur. I will provide more info if requested :D

https://pastebin.com/FBiwLYK0

EDIT: Yes, the server is running ProtocolLib-501
EDIT: And it is OpenJDK-11

**Comment by libraryaddict** [comment]
Caused by Java 16

**Comment by LaurenceBarnes** [comment]
but we don't have Java 16 installed, OpenJDK 11 as I said (I double checked) :(

**Comment by Dymeth** [comment]
Java 11: https://pastebin.com/raw/bnaUZ3gN
Java 16: https://pastebin.com/raw/eTM2zC7y

**Comment by LaurenceBarnes** [comment]
So there definitely is a difference. Interestingly, I did

> Java 11: https://pastebin.com/raw/bnaUZ3gN
> Java 16: https://pastebin.com/raw/eTM2zC7y

so there is a difference. I don't know why we did not get or see it before, but it probably has a reason.

**Comment by libraryaddict** [comment]
My apologies, yes there is an error in Java 16 which looks similar but much more severe.

**Comment by LaurenceBarnes** [comment]
so this error is "harmless"? As to my knowledge, there was no issue so far, and we have been using Java 11 for months now.
Otherwise, is there a fix in the works if I might ask? :D

**Comment by libraryaddict** [comment]
Error is harmless yes

**Comment by mibby** [comment]
Can also confirm receiving the error with Java 11 & LibsDisguise dev 909. Everything seems to function normally outside of the warning.

```
[23:24:13] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v10.0.24-SNAPSHOT
[23:24:13] [Server thread/WARN]: java.lang.NoSuchFieldException: classes
[23:24:13] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
[23:24:13] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.checkPreLoaded(WatcherSanitizer.java:43)
[23:24:13] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.init(WatcherSanitizer.java:68)
[23:24:13] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onLoad(LibsDisguises.java:109)
[23:24:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394)
[23:24:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:274)
[23:24:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[23:24:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[23:24:13] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
