### ISSUE TITLE
DisguiseType.getWatcherClass() is null

### ISSUE THREAD

**Issue by Dymeth** [libraryaddict/LibsDisguises#559]
Hello!

I get an exception when trying to create PlayerDisguise:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because the return value of "me.libraryaddict.disguise.disguisetypes.DisguiseType.getWatcherClass()" is null
	at me.libraryaddict.disguise.disguisetypes.Disguise.createDisguise(Disguise.java:261)
	at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.<init>(PlayerDisguise.java:71)
	at me.libraryaddict.disguise.disguisetypes.PlayerDisguise.<init>(PlayerDisguise.java:51)
	at ...
```

Also I am getting an exception when trying to get the Disguse of an existing Entity (DisguiseAPI.getDisguise(entity)):

```
java.lang.LinkageError: loader constraint violation: when resolving method 'me.libraryaddict.disguise.disguisetypes.Disguise me.libraryaddict.disguise.DisguiseAPI.getDisguise(org.bukkit.entity.Entity)' the class loader org.bukkit.plugin.java.PluginClassLoader @6f8b604a of the current class, ru/dymeth/rpg/session/core/holo/HologramManager, and the class loader org.bukkit.plugin.java.PluginClassLoader @3d1b0189 for the method's defining class, me/libraryaddict/disguise/DisguiseAPI, have different Class objects for the type me/libraryaddict/disguise/disguisetypes/Disguise used in the signature (ru.dymeth.rpg.session.core.holo.HologramManager is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6f8b604a, parent loader 'app'; me.libraryaddict.disguise.DisguiseAPI is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3d1b0189, parent loader 'app')
```

Perhaps this is due to the use of Java 16, so the issue is relative to #557.

OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
Paper version git-Paper-706 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
ProtocolLib version 4.6.1-SNAPSHOT-b501
LibsDisguises version 10.0.24-SNAPSHOT

**Comment by libraryaddict** [comment]
New build, this should be corrected.
