### ISSUE TITLE
java.lang.NoSuchFieldException: classes

### ISSUE THREAD

**Issue by LynxError** [libraryaddict/LibsDisguises#564]
[22:11:14] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v10.0.24
[22:11:14] [Server thread/WARN]: java.lang.NoSuchFieldException: classes
[22:11:14] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:899)
[22:11:14] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.checkPreLoaded(WatcherSanitizer.java:51)
[22:11:14] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.init(WatcherSanitizer.java:77)
[22:11:14] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onLoad(LibsDisguises.java:109)
[22:11:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399)
[22:11:14] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269)
[22:11:14] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[22:11:14] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[22:11:14] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3129/000000000000000000.run(Unknown Source)
[22:11:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:836)

when starting the server I get this error I any support would be great.

LibsDisguises v10.0.24 & Paper 742

**Comment by libraryaddict** [comment]
Error can be safely ignored and is fixed in the latest dev build, and in the next release.
