### ISSUE TITLE
Enable warning

### ISSUE THREAD

**Issue by SnickoDeadMC** [libraryaddict/LibsDisguises#570]
`[15:30:08 INFO]: [LibsDisguises] Loading LibsDisguises v10.0.24
[15:30:08 WARN]: java.lang.NoSuchFieldException: classes
[15:30:08 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
[15:30:08 WARN]:        at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.checkPreLoaded(WatcherSanitizer.java:51)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.libraryaddict.disguise.utilities.reflection.asm.Asm14 (file:/C:/Users/End%20User/Documents/DeadMC/Dev%20server/plugins/LibsDisguises.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of me.libraryaddict.disguise.utilities.reflection.asm.Asm14
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release>
[15:30:08 WARN]:        at me.libraryaddict.disguise.utilities.reflection.asm.WatcherSanitizer.init(WatcherSanitizer.java:77)
[15:30:08 WARN]:        at me.libraryaddict.disguise.LibsDisguises.onLoad(LibsDisguises.java:109)
[15:30:08 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399)
[15:30:08 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269)
[15:30:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[15:30:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[15:30:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)`

Get this warning on enable. Running paper-1.16.5-764. It doesn't seem to affect anything.

**Comment by libraryaddict** [comment]
Can be safely ignored, release coming out soon that fixes it
