### ISSUE TITLE
IllegalArgumentException: Cannot measure the distance between worlds!

### ISSUE THREAD

**Issue by OverlordWeaponry** [libraryaddict/LibsDisguises#571]
There's an issue in the console at times where this error pops up:

`[15:36:05] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot measure distance between tutorial_combat_ecc82c86-dff2-4a90-9a24-0b35db202885 and TutorialIsland
[15:36:05] [Server thread/WARN]: 	at org.bukkit.Location.distanceSquared(Location.java:510)
[15:36:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.constructSpawnPackets(PacketHandlerSpawn.java:175)
[15:36:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.handle(PacketHandlerSpawn.java:64)
[15:36:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:70)
[15:36:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:53)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[15:36:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:243)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1894)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1867)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.a(EntityTrackerEntry.java:313)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:297)
[15:36:05] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor229.invoke(Unknown Source)
[15:36:05] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:36:05] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[15:36:05] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.lambda$refreshTrackers$10(DisguiseUtilities.java:1632)
[15:36:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[15:36:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126)
[15:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[15:36:05] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
`

Looks like it's trying to measure between worlds, but you can't do that?

**Comment by libraryaddict** [comment]
Already fixed in dev builds
