### ISSUE TITLE
NoSuchMethodException: net.minecraft.world.effect.MobEffectList.fromId(int)

### ISSUE THREAD

**Issue by Pugabyte** [libraryaddict/LibsDisguises#577]
Paper 1.17 # 42 
```
[11:47:43] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.25-SNAPSHOT
[11:47:43] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[11:47:43] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_17_R1
[11:47:43] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #943
[11:47:43] [Server thread/INFO]: [LibsDisguises] Build Date: 21/06/2021 12:05
[11:47:43] [Votifier epoll boss/ERROR]: [Votifier] Votifier was not able to bind to /0.0.0.0:8192
[11:47:43] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v10.0.25, build #934, created 07/06/2021 10:27)
[11:47:43] [Server thread/INFO]: [LibsDisguises] Registered to: 39908 (29)
[11:47:43] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[11:47:44] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.effect.MobEffectList.fromId(int)
[11:47:44] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2613)
[11:47:44] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsMethod(ReflectionManager.java:976)
[11:47:44] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsMethod(ReflectionManager.java:988)
[11:47:44] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:140)
[11:47:44] [Server thread/WARN]:        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:210)
[11:47:44] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:47:44] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:47:44] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:47:44] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[11:47:44] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[11:47:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[11:47:44] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[11:47:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[11:47:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[11:47:44] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[11:47:45] [Server thread/ERROR]: [LibsDisguises] <red>Error while loading custom disguise 'libraryaddict': <red>Expected <green>Four ItemStacks (Material:Amount?:Glow?,Material:Amount?:Glow?..)<red>, received <green>GOLD_BOOTS,GOLD_LEGGINGS,GOLD_CHESTPLATE,GOLD_HELMET<red> instead for <green>setArmor
[11:47:45] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise UglyCow2
[11:47:45] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise herobrine_devil
[11:47:45] [Server thread/WARN]: [LibsDisguises] Failed to load 1 custom disguises
[11:47:45] [Server thread/INFO]: [LibsDisguises] Loaded 2 custom disguises
[11:47:45] [Server thread/INFO]: [LibsDisguises] Config is up to date!
```

**Comment by libraryaddict** [comment]
Try update paper, this should be fixed on their end.

**Comment by Pugabyte** [comment]
Assuming you mean [this commit](https://github.com/PaperMC/Paper/commit/a7cddc41532ee01067ea9b9b08e9ff7e63f21f27), that was build 40, I was running 42.

**Comment by libraryaddict** [comment]
Well, the latest is 46 and it looks fine for me.

**Comment by Pugabyte** [comment]
Apologies, caused by https://github.com/PaperMC/paperweight/issues/45
