### ISSUE TITLE
java.lang.NoSuchMethodException: net.minecraft.world.effect.MobEffectList.fromId(int) #957

### ISSUE THREAD

**Issue by taka1945** [libraryaddict/LibsDisguises#583]
[09:19:08] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #957
[09:19:08] [Server thread/INFO]: [LibsDisguises] Build Date: 30/06/2021 21:55
[09:19:08] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v10.0.25, build #934, created 07/06/2021 10:27)
[09:19:08] [Server thread/INFO]: [LibsDisguises] Registered to: xxxxxxx (xx)
[09:19:08] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[09:19:08] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.effect.MobEffectList.fromId(int)
[09:19:08] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2613)
[09:19:08] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsMethod(ReflectionManager.java:980)
[09:19:08] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsMethod(ReflectionManager.java:992)
[09:19:08] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:140)
[09:19:08] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:210)
[09:19:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:19:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:19:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:19:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[09:19:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[09:19:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:714)
[09:19:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:305)
[09:19:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1189)
[09:19:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[09:19:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

server version:
Tuinity version git-Tuinity-7 (MC: 1.17)

**Comment by libraryaddict** [comment]
Tunity needs to fix it
