### ISSUE TITLE
NoSuchMethodException: net.minecraft.world.effect.MobEffectList.fromId(int)

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#587]
LibsDisguises dev 958

```
[14:33:57] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.25-SNAPSHOT
[14:33:57] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[14:33:57] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_17_R1
[14:33:57] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #958
[14:33:57] [Server thread/INFO]: [LibsDisguises] Build Date: 05/07/2021 08:41
[14:33:57] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v10.0.25, build #934, created 07/06/2021 10:27)
[14:33:57] [Server thread/INFO]: [LibsDisguises] Registered to: 819 (18)
[14:33:57] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[14:33:57] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.effect.MobEffectList.fromId(int)
[14:33:57] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2613)
[14:33:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsMethod(ReflectionManager.java:980)
[14:33:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsMethod(ReflectionManager.java:992)
[14:33:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:140)
[14:33:57] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:210)
[14:33:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:33:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:33:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:33:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[14:33:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[14:33:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:716)
[14:33:57] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[14:33:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1193)
[14:33:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[14:33:57] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:33:59] [Server thread/INFO]: [LibsDisguises] Loaded 168 translations for DISGUISES with 0 changed
[14:33:59] [Server thread/INFO]: [LibsDisguises] Loaded 265 translations for MESSAGES with 6 changed
[14:33:59] [Server thread/INFO]: [LibsDisguises] Loaded 183 translations for DISGUISE_OPTIONS with 0 changed
[14:33:59] [Server thread/INFO]: [LibsDisguises] Loaded 1643 translations for DISGUISE_OPTIONS_PARAMETERS with 0 changed
[14:33:59] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise Warrior
[14:33:59] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise Topsy
[14:33:59] [Server thread/INFO]: [LibsDisguises] Loaded 2 custom disguises
[14:33:59] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[14:33:59] [Server thread/INFO]: [LibsDisguises] The author sees Metrics disabled, the author is sad
```

**Comment by libraryaddict** [comment]
Tunity needs to fix it not me
