### ISSUE TITLE
Various issues with disguises in spigot 1.8 using LibsDisguise dev 363.

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#59]
Tagging relevant people.
@libraryaddict, @Byteflux 

Spigot 1.8-R0.1-SNAPSHOT (git-Spigot-4460863-b73cfb0)
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits
LibsDisguise 8.2.6 dev build 363, as of commit https://github.com/libraryaddict/LibsDisguises/commit/b63d855dd600b037020242d52db08b969c9b3eff
http://ci.md-5.net/job/LibsDisguises/363/
ProtocolLib 3.6.3 dev 283.
http://assets.comphenix.net/job/ProtocolLib/283/
Minecraft client: 1.8.1
LibsDisguise Config: http://paste.ubuntu.com/9451175/
(Default config with ViewSelfDisguises set to true.)

---

* /dis firework

You are able to disguise as a firework for a few seconds. After those few seconds post disguising, regardless of standing still or moving, you turn invisible and are frozen in place. The screen shakes repeatedly. Undisguising does not make you reappear, able to move, or stop the screen shaking. Need to relog. 

---

* /dis primed_tnt

Able to disguise as primed tnt. However, after a few seconds, the tnt turns invisible and you are unable to move. Need to relog. 

---

* /dis painting

Does not disguise you as a painting. Instead, disguises you as yourself. Error occurs in server console.

```
[20:08:02] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.server.v1_8_R1.BlockPosition field net.minecraft.server.v1_8_R1.PacketPlayOutSpawnEntityPainting.b to java.lang.Integer
[20:08:02] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[20:08:02] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[20:08:02] [Server thread/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
[20:08:02] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.FieldUtils.writeField(FieldUtils.java:434)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:296)
[20:08:02] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager.constructSpawnPackets(PacketsManager.java:199)
[20:08:02] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:1337)
[20:08:02] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager$3.onPacketSending(PacketsManager.java:779)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:634)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:610)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:362)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:328)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:296)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79)
[20:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140)
[20:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101)
[20:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868)
[20:08:02] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
[20:08:02] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:08:02] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:630)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:614)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector$4.sendServerPacket(NettyProtocolInjector.java:351)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:833)
[20:08:02] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:787)
[20:08:02] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:919)
[20:08:02] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1048)
[20:08:02] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:721)
[20:08:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:08:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694)
[20:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[20:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[20:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[20:08:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

---

* /dis player [name]

Disguising as a specific player does not function. Instead, disguises you as yourself. Multiple errors occur in the server console one after another. 

```
[19:55:27] [Server thread/WARN]: com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 0, Size: 0)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:288)
[19:55:27] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager.constructSpawnPackets(PacketsManager.java:236)
[19:55:27] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:1337)
[19:55:27] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.PacketsManager$3.onPacketSending(PacketsManager.java:779)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:634)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:610)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:362)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:328)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:296)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79)
[19:55:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140)
[19:55:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101)
[19:55:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868)
[19:55:27] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
[19:55:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:55:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:630)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:614)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolInjector$4.sendServerPacket(NettyProtocolInjector.java:351)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:833)
[19:55:27] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:787)
[19:55:27] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:919)
[19:55:27] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1048)
[19:55:27] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:721)
[19:55:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:55:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:55:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694)
[19:55:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[19:55:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[19:55:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[19:55:27] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
```
[19:55:27] [Craft Scheduler Thread - 10/WARN]: java.lang.ClassNotFoundException: net.minecraft.util.com.mojang.authlib.Agent
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.Class.forName0(Native Method)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.Class.forName(Unknown Source)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at me.libraryaddict.disguise.utilities.ReflectionManager.grabProfileAddUUID(ReflectionManager.java:553)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.lookupGameProfile(DisguiseUtilities.java:606)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities$3.run(DisguiseUtilities.java:536)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: java.lang.NullPointerException
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at me.libraryaddict.disguise.utilities.ReflectionManager.getSkullBlob(ReflectionManager.java:518)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.lookupGameProfile(DisguiseUtilities.java:606)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities$3.run(DisguiseUtilities.java:536)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:55:27] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
```
[19:55:27] [Server thread/WARN]: [LibsDisguises] Task #77 for LibsDisguises v8.2.6-SNAPSHOT generated an exception
java.lang.NullPointerException
	at me.libraryaddict.disguise.utilities.DisguiseUtilities$3$1.run(DisguiseUtilities.java:539) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4460863-b73cfb0]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-4460863-b73cfb0]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-4460863-b73cfb0]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-4460863-b73cfb0]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-4460863-b73cfb0]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-4460863-b73cfb0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
```

---

* /dis fishing_hook

Does not disguise you as anything. You are invisible. 

---

* /dis leash_hitch

Leash hitch disguise sometimes turns invisible when moving or flying around. Then reappears when you move again.

---

* /dis itemframe

Does not disguise you as an itemframe. Instead, crashes the client. No errors occur in the server console. Summarized client crash log with relevant information.

```
---- Minecraft Crash Report ----
// You're mean.

Time: 12/9/14 8:12 PM
Description: Rendering entity in world

java.lang.ClassCastException: java.lang.String cannot be cast to amg
	at xy.f(SourceFile:112)
	at adl.o(SourceFile:124)
	at cqg.a(SourceFile:53)
	at cqg.a(SourceFile:26)
	at cpt.a(SourceFile:294)
	at cpt.a(SourceFile:259)
	at cpt.a(SourceFile:226)
	at ckn.a(SourceFile:591)
	at cjh.a(SourceFile:1231)
	at cjh.a(SourceFile:1136)
	at cjh.b(SourceFile:989)
	at bss.at(SourceFile:906)
	at bss.a(SourceFile:317)
	at net.minecraft.client.main.Main.main(SourceFile:124)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at xy.f(SourceFile:112)
	at adl.o(SourceFile:124)
	at cqg.a(SourceFile:53)
	at cqg.a(SourceFile:26)

-- Entity being rendered --
Details:
	Entity Type: ItemFrame (adl)
	Entity ID: -10
	Entity Name: entity.ItemFrame.name
	Entity's Exact location: -315.72, 63.00, 371.38
	Entity's Block location: -316.00,63.00,371.00 - World: (-316,63,371), Chunk: (at 4,3,3 in -20,23; contains blocks -320,0,368 to -305,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: cqg@3da55998
	Location: 0.98,0.00,-0.00 - World: (0,0,-1), Chunk: (at 0,0,15 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 80.15625
	Delta: 0.7362483
Stacktrace:
	at cpt.a(SourceFile:294)
	at cpt.a(SourceFile:259)
	at cpt.a(SourceFile:226)
	at ckn.a(SourceFile:591)
	at cjh.a(SourceFile:1231)
	at cjh.a(SourceFile:1136)
```

**Comment by NavidK0** [comment]
Resolved.
