### ISSUE TITLE
Commands since Java 16 not working

### ISSUE THREAD

**Issue by JeffHD** [libraryaddict/LibsDisguises#598]
Since i upgraded java to version 16, the commands dont work anymore. I get the message that i dont have the permission.
Error in console:
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at net.alpenblock.bungeeperms.PermissionsResolver.hasNormalSequential(PermissionsResolver.java:143)
        at net.alpenblock.bungeeperms.PermissionsResolver.hasPerm(PermissionsResolver.java:98)
        at net.alpenblock.bungeeperms.User.hasPerm(User.java:220)
        at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInWorld(PermissionsChecker.java:254)
        at net.alpenblock.bungeeperms.platform.bukkit.BPPermissible.hasPermission(BPPermissible.java:138)
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:207)
        at me.libraryaddict.disguise.utilities.parser.DisguisePermissions.loadPermissions(DisguisePermissions.java:196)
        at me.libraryaddict.disguise.utilities.parser.DisguisePermissions.<init>(DisguisePermissions.java:110)
        at me.libraryaddict.disguise.utilities.parser.DisguiseParser.getPermissions(DisguiseParser.java:416)
        at me.libraryaddict.disguise.commands.DisguiseBaseCommand.getPermissions(DisguiseBaseCommand.java:305)
        at me.libraryaddict.disguise.commands.disguise.DisguiseCommand.onCommand(DisguiseCommand.java:36)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168)
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983)
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936)
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252)
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206)
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
        at java.base/java.lang.Thread.run(Thread.java:831)

I dont know if its caused from the permission plugin or from libsdisguises but i have no problems with other plugins and the index out of bounds seems strange to me

**Comment by libraryaddict** [comment]
Your bungeeperms has the issue.

As for why, it's their problem as I don't know. Probably caused by weird permission system I use, but no good excuse tbh.
