### ISSUE TITLE
It keeps disabling

### ISSUE THREAD

**Issue by roast247** [libraryaddict/LibsDisguises#608]
[08:25:35 ERROR]: Error occurred while enabling LibsDisguises v10.0.26 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDescription()" because the return value of "com.comphenix.protocol.ProtocolLibrary.getPlugin()" is null
        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:175) ~[LibsDisguises-10.0.26-Free.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-157]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-157]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-157]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-157]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-157]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-157]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-157]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-157]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-157]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by libraryaddict** [comment]
I need your full server log. Upload your latest.log to pastebin or similar site.

**Comment by roast247** [comment]
user error lol, I didn't update the "Protocol Lib" plugin, sorry for the inconvenience
