### ISSUE TITLE
Libs Throwing massive errors

### ISSUE THREAD

**Issue by Scyrizu** [libraryaddict/LibsDisguises#609]
> [14.08 00:16:46] [Server] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.26
[14.08 00:16:46] [Server] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises-10.0.26-Premium.jar
[14.08 00:16:46] [Server] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_17_R1
[14.08 00:16:46] [Server] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #972
[14.08 00:16:46] [Server] [Server thread/INFO]: [LibsDisguises] Build Date: 16/07/2021 20:00
[14.08 00:16:46] [Server] [Server thread/INFO]: [LibsDisguises] Registered to: 209795 (32)
[14.08 00:16:46] [Server] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[14.08 00:16:48] [Server] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class me.libraryaddict.disguise.DisguiseAPI
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.FlagWatcher.sendItemStack(FlagWatcher.java:923)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.LibsEquipment.setItem(LibsEquipment.java:57)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.LibsEquipment.setBoots(LibsEquipment.java:123)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.LibsEquipment.setArmorContents(LibsEquipment.java:133)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.FlagWatcher.setArmor(FlagWatcher.java:446)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.parser.DisguiseParser.callMethods(DisguiseParser.java:1050)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.parser.DisguiseParser.parseDisguise(DisguiseParser.java:929)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.parser.DisguiseParser.parseTestDisguise(DisguiseParser.java:641)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.DisguiseConfig.addCustomDisguise(DisguiseConfig.java:954)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.DisguiseConfig.loadCustomDisguises(DisguiseConfig.java:917)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.DisguiseConfig.loadConfig(DisguiseConfig.java:699)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:221)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:505)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:419)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14.08 00:16:48] [Server] [Server thread/WARN]: [LibsDisguises] Failed to load 1 custom disguises
[14.08 00:16:48] [Server] [Server thread/INFO]: [LibsDisguises] Loaded 0 custom disguises
[14.08 00:16:48] [Server] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[14.08 00:16:48] [Server] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.createDisguise(Disguise.java:264)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.MiscDisguise.apply(MiscDisguise.java:79)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.MiscDisguise.<init>(MiscDisguise.java:64)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.MiscDisguise.<init>(MiscDisguise.java:20)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.parser.DisguiseParser.createDefaultMethods(DisguiseParser.java:56)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:223)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:505)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:419)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14.08 00:16:48] [Server] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.libraryaddict.disguise.DisguiseAPI
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.FlagWatcher.sendData(FlagWatcher.java:821)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.watchers.AreaEffectCloudWatcher.setColor(AreaEffectCloudWatcher.java:51)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.watchers.AreaEffectCloudWatcher.<init>(AreaEffectCloudWatcher.java:24)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	... 21 more
[14.08 00:16:48] [Server] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.parser.DisguiseParser.createDefaultMethods(DisguiseParser.java:65)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:223)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:505)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:419)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14.08 00:16:48] [Server] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.libraryaddict.disguise.DisguiseAPI
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.FlagWatcher.sendData(FlagWatcher.java:821)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.watchers.AreaEffectCloudWatcher.setColor(AreaEffectCloudWatcher.java:51)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	at me.libraryaddict.disguise.disguisetypes.watchers.AreaEffectCloudWatcher.<init>(AreaEffectCloudWatcher.java:24)
[14.08 00:16:48] [Server] [Server thread/WARN]: 	... 17 more

**Comment by libraryaddict** [comment]
Looks like you have a plugin shading Libs Disguises inside itself.
Remove other plugins until issue disappears
