### ISSUE TITLE
WARN

### ISSUE THREAD

**Issue by tncc2k** [libraryaddict/LibsDisguises#620]
PaperMC 1.12.2
LibsDisguises-10.0.26-Free
MythicMobs-4.12.0

The wing scene appears when using the command:
/mm s ZombieX
Only show warning once until server restart

WARN:
[06:08:23 INFO]: admin issued server command: /mm m s ZombieX
[06:08:24 WARN]: java.lang.NoSuchMethodException: java.util.Collections$SingletonList.<init>()
[06:08:24 WARN]: at java.lang.Class.getConstructor0(Unknown Source)
[06:08:24 WARN]: at java.lang.Class.getConstructor(Unknown Source)
[06:08:24 WARN]: at com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[06:08:24 WARN]: at com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[06:08:24 WARN]: at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[06:08:24 WARN]: at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[06:08:24 WARN]: at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[06:08:24 WARN]: at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[06:08:24 WARN]: at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[06:08:24 WARN]: at me.libraryaddict.disguise.utilities.DisguiseUtilities.getTabPacket(DisguiseUtilities.java:2669)
[06:08:24 WARN]: at me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.doPacketRemoval(PlayerSkinHandler.java:371)
[06:08:24 WARN]: at me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.lambda$tryProcess$12(PlayerSkinHandler.java:398)
[06:08:24 WARN]: at java.util.ArrayList.forEach(Unknown Source)
[06:08:24 WARN]: at me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.tryProcess(PlayerSkinHandler.java:398)
[06:08:24 WARN]: at me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.onMove(PlayerSkinHandler.java:409)
[06:08:24 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor174.execute(Unknown Source)
[06:08:24 WARN]: at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[06:08:24 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[06:08:24 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[06:08:24 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:711)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[06:08:24 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[06:08:24 WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[06:08:24 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[06:08:24 WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by libraryaddict** [comment]
Use /ld protocollib
