### ISSUE TITLE
latest version spams console when using disguise

### ISSUE THREAD

**Issue by snowgears** [libraryaddict/LibsDisguises#623]
[22:07:39] [Server thread/WARN]: java.lang.NoSuchMethodException: java.util.Collections$SingletonList.<init>()
[22:07:39] [Server thread/WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[22:07:39] [Server thread/WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2238)
[22:07:39] [Server thread/WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[22:07:39] [Server thread/WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[22:07:39] [Server thread/WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[22:07:39] [Server thread/WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[22:07:39] [Server thread/WARN]:        at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[22:07:39] [Server thread/WARN]:        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[22:07:39] [Server thread/WARN]:        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[22:07:39] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.getTabPacket(DisguiseUtilities.java:2669)
[22:07:39] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.doPacketRemoval(PlayerSkinHandler.java:371)
[22:07:39] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.lambda$tryProcess$12(PlayerSkinHandler.java:398)
[22:07:39] [Server thread/WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[22:07:39] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.tryProcess(PlayerSkinHandler.java:398)
[22:07:39] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.onMove(PlayerSkinHandler.java:409)
[22:07:39] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:07:39] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[22:07:39] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:07:39] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[22:07:39] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[22:07:39] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:07:39] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[22:07:39] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[22:07:39] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1239)
[22:07:39] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(SourceFile:114)
[22:07:39] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:64)
[22:07:39] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[22:07:39] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[22:07:39] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[22:07:39] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:07:39] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[22:07:39] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148)
[22:07:39] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141)
[22:07:39] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110)
[22:07:39] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124)
[22:07:39] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054)
[22:07:39] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[22:07:39] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by libraryaddict** [comment]
Use /ld protocollib

**Comment by snowgears** [comment]
Thank you!
