### ISSUE TITLE
[Bug] NoSuchMethodException thrown once per server "lifetime"

### ISSUE THREAD

**Issue by jaylawl** [libraryaddict/LibsDisguises#628]
This exception is thrown when applying a player disguise (via injecting a game profile as a string) to either a player or any other entity.

It only pops up once after restarting the server upon applying the disguise. After that it doesn't happen again; unless the server is restarted.

Running
- LibsDisguises FREE 10.0.26
- ProtocolLib 4.7.0
- git-Paper-279 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6de48db)

Thank you!

```[01:56:34 WARN]: java.lang.NoSuchMethodException: java.util.Collections$SingletonList.<init>()
[01:56:34 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[01:56:34 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2238)
[01:56:34 WARN]:        at ProtocolLib 4.7.0.jar//com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[01:56:34 WARN]:        at ProtocolLib 4.7.0.jar//com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[01:56:34 WARN]:        at ProtocolLib 4.7.0.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[01:56:34 WARN]:        at ProtocolLib 4.7.0.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[01:56:34 WARN]:        at ProtocolLib 4.7.0.jar//com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[01:56:34 WARN]:        at ProtocolLib 4.7.0.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[01:56:34 WARN]:        at ProtocolLib 4.7.0.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[01:56:34 WARN]:        at LibsDisguises-10.0.26-Free.jar//me.libraryaddict.disguise.utilities.DisguiseUtilities.getTabPacket(DisguiseUtilities.java:2669)
[01:56:34 WARN]:        at LibsDisguises-10.0.26-Free.jar//me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.doPacketRemoval(PlayerSkinHandler.java:371)
[01:56:34 WARN]:        at LibsDisguises-10.0.26-Free.jar//me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.lambda$tryProcess$12(PlayerSkinHandler.java:398)
[01:56:34 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[01:56:34 WARN]:        at LibsDisguises-10.0.26-Free.jar//me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.tryProcess(PlayerSkinHandler.java:398)
[01:56:34 WARN]:        at LibsDisguises-10.0.26-Free.jar//me.libraryaddict.disguise.utilities.listeners.PlayerSkinHandler.onMove(PlayerSkinHandler.java:409)
[01:56:34 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor80.execute(Unknown Source)
[01:56:34 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[01:56:34 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:56:34 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:56:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[01:56:34 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1477)
[01:56:34 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(PacketPlayInFlying.java:114)
[01:56:34 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPosition.a(PacketPlayInFlying.java:42)
[01:56:34 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[01:56:34 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:56:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[01:56:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[01:56:34 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418)
[01:56:34 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[01:56:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[01:56:34 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396)
[01:56:34 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)
[01:56:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[01:56:34 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367)
[01:56:34 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278)
[01:56:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[01:56:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

Example code usage that causes this (among others):
```
PlayerDisguise playerDisguise = new PlayerDisguise("").setSkin(gameProfile);
playerDisguise.setEntity(player);
playerDisguise.startDisguise();
```
`gameProfile` just being a String holding game profile data (definitly valid data!)

Additional info:
- This exception despite being thrown, does not cause the disguise to fail. Everything looks fine ingame as far as i can tell

**Comment by jaylawl** [comment]
This issue was fixed by upgrading to ProtocolLib 4.8.0
