### ISSUE TITLE
IllegalStateException: WatcherMethod

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#638]
LibsDisguises dev 1055.
Purpur dev 1561

Noticed these two errors after updating dev builds.

```
[01:29:48] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.27-SNAPSHOT
[01:29:48] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[01:29:48] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_18_R1
[01:29:48] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #1055
[01:29:48] [Server thread/INFO]: [LibsDisguises] Build Date: 17/02/2022 07:57
[01:29:48] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v10.0.27, build #1035, created 23/12/2021 04:30)
[01:29:48] [Server thread/INFO]: [LibsDisguises] Registered to: 819 (18)
[01:29:48] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[01:29:49] [Paper Async Chunk Task Thread #0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.NullPointerException: Cannot read field "nextInKToVBucket" because "bucketEntry" is null
	at com.google.common.collect.HashBiMap.delete(HashBiMap.java:155) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:316) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:290) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.core.MappedRegistry.registerMapping(MappedRegistry.java:81) ~[?:?]
	at net.minecraft.core.MappedRegistry.registerOrOverride(MappedRegistry.java:115) ~[?:?]
	at net.minecraft.resources.RegistryReadOps.readAndRegisterElement(RegistryReadOps.java:124) ~[purpur-1.18.1.jar:git-Purpur-1561]
	at net.minecraft.resources.RegistryReadOps.lambda$decodeElement$3(RegistryReadOps.java:80) ~[purpur-1.18.1.jar:git-Purpur-1561]
	at net.minecraft.resources.RegistryFileCodec.decode(RegistryFileCodec.java:50) ~[purpur-1.18.1.jar:git-Purpur-1561]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:324) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[purpur-1.18.1.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[purpur-1.18.1.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[purpur-1.18.1.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[purpur-1.18.1.jar:git-Purpur-1561]
	at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[purpur-1.18.1.jar:git-Purpur-1561]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[purpur-1.18.1.jar:git-Purpur-1561]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[purpur-1.18.1.jar:git-Purpur-1561]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[purpur-1.18.1.jar:git-Purpur-1561]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[purpur-1.18.1.jar:git-Purpur-1561]
[01:29:54] [Server thread/INFO]: [LibsDisguises] Loaded 168 translations for DISGUISES with 0 changed
[01:29:54] [Server thread/INFO]: [LibsDisguises] Loaded 266 translations for MESSAGES with 6 changed
[01:29:54] [Server thread/INFO]: [LibsDisguises] Loaded 185 translations for DISGUISE_OPTIONS with 0 changed
[01:29:54] [Server thread/INFO]: [LibsDisguises] Loaded 1649 translations for DISGUISE_OPTIONS_PARAMETERS with 0 changed
[01:29:54] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise Warrior
[01:29:54] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise Topsy
[01:29:54] [Server thread/INFO]: [LibsDisguises] Loaded 2 custom disguises
[01:29:54] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[01:29:54] [Server thread/WARN]: java.lang.IllegalStateException: WatcherMethod{watcherClass=class me.libraryaddict.disguise.disguisetypes.FlagWatcher, method=MethodHandle(FlagWatcher,String)void, name='setCustomName', returnType=void, param=class java.lang.String, randomDefault=false, hideFromTab=false} has conflicting values in class WatcherMethod{watcherClass=class me.libraryaddict.disguise.disguisetypes.FlagWatcher, method=MethodHandle(FlagWatcher,String)void, name='setCustomName', returnType=void, param=class java.lang.String, randomDefault=false, hideFromTab=false}! This means it expected the same value again but received a different value on a different disguise! Foobar is not the same as null!
[01:29:54] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.utilities.parser.DisguiseParser.addWatcherDefault(DisguiseParser.java:315)
[01:29:54] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.utilities.parser.DisguiseParser.createDefaultMethods(DisguiseParser.java:151)
[01:29:54] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:241)
[01:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[01:29:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561)
[01:29:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475)
[01:29:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732)
[01:29:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508)
[01:29:54] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349)
[01:29:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
[01:29:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[01:29:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:29:54] [Server thread/INFO]: [LibsDisguises] The author sees Metrics disabled, the author is sad
```

Downgrading to dev 1053, no erorrs at initialization.

**Comment by mibby** [comment]
Still an issue as of dev 1056.

```
[03:12:47] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.27-SNAPSHOT
[03:12:47] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[03:12:47] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_18_R1
[03:12:47] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #1056
[03:12:47] [Server thread/INFO]: [LibsDisguises] Build Date: 17/02/2022 09:58
[03:12:47] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v10.0.27, build #1035, created 23/12/2021 04:30)
[03:12:47] [Server thread/INFO]: [LibsDisguises] Registered to: 819 (18)
[03:12:47] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[03:12:51] [pool-25-thread-1/INFO]: [PlotSquared/BukkitPlatform] (UUID) PlotSquared will fetch UUIDs in groups of 200
[03:12:51] [pool-25-thread-1/INFO]: [PlotSquared/BukkitPlatform] (UUID) PlotSquared has cached all UUIDs
[03:12:53] [Server thread/INFO]: [LibsDisguises] Loaded 168 translations for DISGUISES with 0 changed
[03:12:53] [Server thread/INFO]: [LibsDisguises] Loaded 266 translations for MESSAGES with 6 changed
[03:12:53] [Server thread/INFO]: [LibsDisguises] Loaded 185 translations for DISGUISE_OPTIONS with 0 changed
[03:12:53] [Server thread/INFO]: [LibsDisguises] Loaded 1649 translations for DISGUISE_OPTIONS_PARAMETERS with 0 changed
[03:12:53] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise Warrior
[03:12:53] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise Topsy
[03:12:53] [Server thread/INFO]: [LibsDisguises] Loaded 2 custom disguises
[03:12:53] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[03:12:53] [Server thread/WARN]: java.lang.IllegalStateException: WatcherMethod{watcherClass=class me.libraryaddict.disguise.disguisetypes.FlagWatcher, method=MethodHandle(FlagWatcher,String)void, name='setCustomName', returnType=void, param=class java.lang.String, randomDefault=false, hideFromTab=false} has conflicting values in class WatcherMethod{watcherClass=class me.libraryaddict.disguise.disguisetypes.FlagWatcher, method=MethodHandle(FlagWatcher,String)void, name='setCustomName', returnType=void, param=class java.lang.String, randomDefault=false, hideFromTab=false}! This means it expected the same value again but received a different value on a different disguise! Foobar is not the same as null!
[03:12:53] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.utilities.parser.DisguiseParser.addWatcherDefault(DisguiseParser.java:315)
[03:12:53] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.utilities.parser.DisguiseParser.createDefaultMethods(DisguiseParser.java:151)
[03:12:53] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:241)
[03:12:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:12:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[03:12:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[03:12:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561)
[03:12:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475)
[03:12:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732)
[03:12:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508)
[03:12:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349)
[03:12:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
[03:12:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[03:12:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:12:53] [Server thread/INFO]: [LibsDisguises] The author sees Metrics disabled, the author is sad
```
