### ISSUE TITLE
Failed to find NMS class: world.entity.player.ProfilePublicKey | ProtocolLib-568 ?

### ISSUE THREAD

**Issue by x1p** [libraryaddict/LibsDisguises#659]
Getting this error when a player joins the game:
```
[10:45:27] [Server thread/ERROR]: [LibsDisguises] Unhandled exception number 32 occurred in onPacketSending(PacketEvent) for LibsDisguises
java.lang.RuntimeException: Failed to find NMS class: world.entity.player.ProfilePublicKey
at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$1(MinecraftReflection.java:2079) ~[ProtocolLib-568.jar:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2079) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.utility.MinecraftReflection.getProfilePublicKeyClass(MinecraftReflection.java:2274) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.utility.MinecraftReflection.getProfilePublicKeyDataClass(MinecraftReflection.java:2278) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.wrappers.PlayerInfoData$1.getSpecific(PlayerInfoData.java:181) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.wrappers.PlayerInfoData$1.getSpecific(PlayerInfoData.java:111) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getSpecificList(BukkitConverters.java:319) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters.access$000(BukkitConverters.java:89) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:363) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:360) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:43) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib-568.jar:?]
at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerTabList.onPacketSending(PacketListenerTabList.java:35) ~[LibsDisguises-1092.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib-568.jar:?]
at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib-568.jar:?]
at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
at net.minecraft.network.Connection.processQueue(Connection.java:530) ~[?:?]
at net.minecraft.network.Connection.flushQueue(Connection.java:493) ~[?:?]
at net.minecraft.network.Connection.send(Connection.java:401) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2123) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2109) ~[?:?]
at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:393) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:320) ~[?:?]
at net.minecraft.network.Connection.tick(Connection.java:576) ~[?:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1651) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

LibsDisguises build 1092
ProtocolLib buid 568
Paper (fork) 1.18.2 (planning to go to 1.19 real soon)

**Comment by libraryaddict** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/1644

Download from here and replace the jar

https://www.spigotmc.org/resources/protocollib.1997/
