### ISSUE TITLE
no 1.19.1 update on spigot, but here? :(

### ISSUE THREAD

**Issue by MelonCraftDE** [libraryaddict/LibsDisguises#665]
no 1.19.1 update on spigot, but here? :(

**Comment by Doc94** [comment]
Currently its broken the last build for 1.19.1 (or for my case for the remapped)

**Comment by TheModdersDen** [comment]
Yup. 1.19.1 doesn't work (yet). Can confirm this myself. Get the following error when I try to enable:
`[Server thread/ERROR]: Error occurred while enabling LibsDisguises v10.0.29-SNAPSHOT (Is it up to date?)
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Float (java.lang.Integer and java.lang.Float are in module java.base of loader 'bootstrap')
	at me.libraryaddict.disguise.utilities.reflection.v1_19.ReflectionManager.getSoundModifier(ReflectionManager.java:276) ~[LibsDisguises-DEV.jar:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getSoundModifier(ReflectionManager.java:1163) ~[LibsDisguises-DEV.jar:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.createNMSValues(ReflectionManager.java:2329) ~[LibsDisguises-DEV.jar:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.registerValues(ReflectionManager.java:2123) ~[LibsDisguises-DEV.jar:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:240) ~[LibsDisguises-DEV.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-97]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-97]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-97]
`

**Comment by libraryaddict** [comment]
https://cdn.discordapp.com/attachments/579140593293328414/1002233658465341581/LibsDisguises.jar

Not sure if you can download it outside of discord.

But the pinned link. Basically jenkins can't compile it atm.

**Comment by TheModdersDen** [comment]
Thanks. Will give it a try.

**Comment by TheModdersDen** [comment]
Works on the latest version of PaperMC, or so it seems... :)
![image](https://user-images.githubusercontent.com/3487232/182065173-9ec7abfd-b39c-45f0-9020-059b0ec73ad2.png)

**Comment by Mr-KayJayDee** [comment]
Can someone upload an actual version without discord ? Because for me the link seems broken. Thanks ^^
