### ISSUE TITLE
1.19.3 incompatibility?

### ISSUE THREAD

**Issue by AndrewChqng** [libraryaddict/LibsDisguises#679]
Hi, not sure if it's my side but thought I'd just file this in case you can help :)
```
[23:10:33] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v10.0.31-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R1/inventory/CraftItemStack
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getReflectionManager(ReflectionManager.java:790) ~[LibsDisguises.jar:?]
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:195) ~[LibsDisguises.jar:?]
        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:236) ~[LibsDisguises.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1873]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R1.inventory.CraftItemStack
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more
```

**Comment by DexterSK** [comment]
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R1/inventory/CraftItemStack

it doesn't support 1.19.3 at the moment so we need to wait for update
