### ISSUE TITLE
Unhandled exception occurred in onPacketSending(PacketEvent) for LibsDisguises

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#680]
Paper dev 347 (Spigot 1.19.3) & Purpur dev 1876 (Paper 1.19.3)
ProtocolLib dev 608 https://ci.dmulloy2.net/job/ProtocolLib/608/
LibsDisguise dev 1146 https://ci.md-5.net/job/LibsDisguises/1146/
Citizens2 dev 2834 https://ci.citizensnpcs.co/job/Citizens2/2834/

Updated to 1.19.3. Error seems to occur every time someone logs in.

```
[02:50:05] [User Authenticator #0/INFO]: UUID of player player is uuid
[02:50:05] [Server thread/ERROR]: [LibsDisguises] Unhandled exception occurred in onPacketSending(PacketEvent) for LibsDisguises
java.util.NoSuchElementException: null
	at java.util.RegularEnumSet$EnumSetIterator.next(RegularEnumSet.java:103) ~[?:?]
	at java.util.RegularEnumSet$EnumSetIterator.next(RegularEnumSet.java:79) ~[?:?]
	at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerTabList.onPacketSending(PacketListenerTabList.java:53) ~[LibsDisguises.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:430) ~[?:?]
	at net.minecraft.network.Connection.processQueue(Connection.java:547) ~[?:?]
	at net.minecraft.network.Connection.flushQueue(Connection.java:503) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:398) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2248) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2234) ~[?:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:340) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:585) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1594) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:50:05] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket@5a1880d2[
    a=[ADD_PLAYER, INITIALIZE_CHAT, UPDATE_GAME_MODE, UPDATE_LISTED, UPDATE_LATENCY, UPDATE_DISPLAY_NAME]
    b=[b[profileId=00000000-0000-0000-0000-000000000001, profile=com.mojang.authlib.GameProfile@7394b270[id=00000000-0000-0000-0000-000000000001,name=|slot_11,properties={textures=[com.mojang.authlib.properties.Property@6b56c455]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000015, profile=com.mojang.authlib.GameProfile@616cc656[id=00000000-0000-0000-0000-000000000015,name=|slot_31,properties={textures=[com.mojang.authlib.properties.Property@4e4cd6e0]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000029, profile=com.mojang.authlib.GameProfile@935b28[id=00000000-0000-0000-0000-000000000029,name=|slot_51,properties={textures=[com.mojang.authlib.properties.Property@28fabb5a]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000003d, profile=com.mojang.authlib.GameProfile@2f6eb13e[id=00000000-0000-0000-0000-00000000003d,name=|slot_71,properties={textures=[com.mojang.authlib.properties.Property@3e9d1602]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000002, profile=com.mojang.authlib.GameProfile@49ae3241[id=00000000-0000-0000-0000-000000000002,name=|slot_12,properties={textures=[com.mojang.authlib.properties.Property@2b951815]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000016, profile=com.mojang.authlib.GameProfile@4ef70354[id=00000000-0000-0000-0000-000000000016,name=|slot_32,properties={textures=[com.mojang.authlib.properties.Property@1a886fc1]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000002a, profile=com.mojang.authlib.GameProfile@54274bb9[id=00000000-0000-0000-0000-00000000002a,name=|slot_52,properties={textures=[com.mojang.authlib.properties.Property@d4d3e2a]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000003e, profile=com.mojang.authlib.GameProfile@e9ae742[id=00000000-0000-0000-0000-00000000003e,name=|slot_72,properties={textures=[com.mojang.authlib.properties.Property@22d391b]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000003, profile=com.mojang.authlib.GameProfile@361ee0ea[id=00000000-0000-0000-0000-000000000003,name=|slot_13,properties={textures=[com.mojang.authlib.properties.Property@36ec82aa]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000017, profile=com.mojang.authlib.GameProfile@4085b8de[id=00000000-0000-0000-0000-000000000017,name=|slot_33,properties={textures=[com.mojang.authlib.properties.Property@13b0d88c]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000002b, profile=com.mojang.authlib.GameProfile@2e9159f4[id=00000000-0000-0000-0000-00000000002b,name=|slot_53,properties={textures=[com.mojang.authlib.properties.Property@318a9654]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000003f, profile=com.mojang.authlib.GameProfile@77e81b93[id=00000000-0000-0000-0000-00000000003f,name=|slot_73,properties={textures=[com.mojang.authlib.properties.Property@21d8ec0c]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000004, profile=com.mojang.authlib.GameProfile@36b0bc34[id=00000000-0000-0000-0000-000000000004,name=|slot_14,properties={textures=[com.mojang.authlib.properties.Property@3afc1e0b]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000018, profile=com.mojang.authlib.GameProfile@5b1eb174[id=00000000-0000-0000-0000-000000000018,name=|slot_34,properties={textures=[com.mojang.authlib.properties.Property@379b6f08]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000002c, profile=com.mojang.authlib.GameProfile@7f640d1a[id=00000000-0000-0000-0000-00000000002c,name=|slot_54,properties={textures=[com.mojang.authlib.properties.Property@21512165]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000040, profile=com.mojang.authlib.GameProfile@4867a5e6[id=00000000-0000-0000-0000-000000000040,name=|slot_74,properties={textures=[com.mojang.authlib.properties.Property@5e7a21c9]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000005, profile=com.mojang.authlib.GameProfile@7b85f1c2[id=00000000-0000-0000-0000-000000000005,name=|slot_15,properties={textures=[com.mojang.authlib.properties.Property@4cdc0344]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000019, profile=com.mojang.authlib.GameProfile@553e7ad7[id=00000000-0000-0000-0000-000000000019,name=|slot_35,properties={textures=[com.mojang.authlib.properties.Property@76792ff7]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000002d, profile=com.mojang.authlib.GameProfile@aeda1b7[id=00000000-0000-0000-0000-00000000002d,name=|slot_55,properties={textures=[com.mojang.authlib.properties.Property@582c26f2]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000041, profile=com.mojang.authlib.GameProfile@7f506d99[id=00000000-0000-0000-0000-000000000041,name=|slot_75,properties={textures=[com.mojang.authlib.properties.Property@f14d6f0]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000006, profile=com.mojang.authlib.GameProfile@2b0f8850[id=00000000-0000-0000-0000-000000000006,name=|slot_16,properties={textures=[com.mojang.authlib.properties.Property@74da7841]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000001a, profile=com.mojang.authlib.GameProfile@d41a724[id=00000000-0000-0000-0000-00000000001a,name=|slot_36,properties={textures=[com.mojang.authlib.properties.Property@7ab4ed4]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000002e, profile=com.mojang.authlib.GameProfile@6a464f22[id=00000000-0000-0000-0000-00000000002e,name=|slot_56,properties={textures=[com.mojang.authlib.properties.Property@2b822621]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000042, profile=com.mojang.authlib.GameProfile@1686db56[id=00000000-0000-0000-0000-000000000042,name=|slot_76,properties={textures=[com.mojang.authlib.properties.Property@55f5cb5d]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000007, profile=com.mojang.authlib.GameProfile@419c8cde[id=00000000-0000-0000-0000-000000000007,name=|slot_17,properties={textures=[com.mojang.authlib.properties.Property@95bfce6]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000001b, profile=com.mojang.authlib.GameProfile@41646b4e[id=00000000-0000-0000-0000-00000000001b,name=|slot_37,properties={textures=[com.mojang.authlib.properties.Property@5596eb33]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000002f, profile=com.mojang.authlib.GameProfile@1903031f[id=00000000-0000-0000-0000-00000000002f,name=|slot_57,properties={textures=[com.mojang.authlib.properties.Property@23321eec]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000043, profile=com.mojang.authlib.GameProfile@39ff3702[id=00000000-0000-0000-0000-000000000043,name=|slot_77,properties={textures=[com.mojang.authlib.properties.Property@7c74b94e]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000008, profile=com.mojang.authlib.GameProfile@1c20a69f[id=00000000-0000-0000-0000-000000000008,name=|slot_18,properties={textures=[com.mojang.authlib.properties.Property@79efc774]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000001c, profile=com.mojang.authlib.GameProfile@7e7c904e[id=00000000-0000-0000-0000-00000000001c,name=|slot_38,properties={textures=[com.mojang.authlib.properties.Property@76b1eb4f]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000030, profile=com.mojang.authlib.GameProfile@7f666f65[id=00000000-0000-0000-0000-000000000030,name=|slot_58,properties={textures=[com.mojang.authlib.properties.Property@7057a102]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000044, profile=com.mojang.authlib.GameProfile@3f6110ac[id=00000000-0000-0000-0000-000000000044,name=|slot_78,properties={textures=[com.mojang.authlib.properties.Property@1241dc95]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000009, profile=com.mojang.authlib.GameProfile@26ec4d81[id=00000000-0000-0000-0000-000000000009,name=|slot_19,properties={textures=[com.mojang.authlib.properties.Property@8e74fb5]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000001d, profile=com.mojang.authlib.GameProfile@3c0857f2[id=00000000-0000-0000-0000-00000000001d,name=|slot_39,properties={textures=[com.mojang.authlib.properties.Property@62322b9b]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000031, profile=com.mojang.authlib.GameProfile@70d90a51[id=00000000-0000-0000-0000-000000000031,name=|slot_59,properties={textures=[com.mojang.authlib.properties.Property@38ca9a12]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000045, profile=com.mojang.authlib.GameProfile@478a8096[id=00000000-0000-0000-0000-000000000045,name=|slot_79,properties={textures=[com.mojang.authlib.properties.Property@6ad0084c]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000000a, profile=com.mojang.authlib.GameProfile@34e4da3[id=00000000-0000-0000-0000-00000000000a,name=|slot_20,properties={textures=[com.mojang.authlib.properties.Property@1be9cf77]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000001e, profile=com.mojang.authlib.GameProfile@7d873dff[id=00000000-0000-0000-0000-00000000001e,name=|slot_40,properties={textures=[com.mojang.authlib.properties.Property@419b881]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000032, profile=com.mojang.authlib.GameProfile@45343b9c[id=00000000-0000-0000-0000-000000000032,name=|slot_60,properties={textures=[com.mojang.authlib.properties.Property@58c4ee0f]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000046, profile=com.mojang.authlib.GameProfile@56a98d9c[id=00000000-0000-0000-0000-000000000046,name=|slot_80,properties={textures=[com.mojang.authlib.properties.Property@752e925f]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000000b, profile=com.mojang.authlib.GameProfile@27fbf1bf[id=00000000-0000-0000-0000-00000000000b,name=|slot_21,properties={textures=[com.mojang.authlib.properties.Property@1fa69633]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000001f, profile=com.mojang.authlib.GameProfile@63d7587a[id=00000000-0000-0000-0000-00000000001f,name=|slot_41,properties={textures=[com.mojang.authlib.properties.Property@750d902d]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000033, profile=com.mojang.authlib.GameProfile@7db6747[id=00000000-0000-0000-0000-000000000033,name=|slot_61,properties={textures=[com.mojang.authlib.properties.Property@5394a003]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000047, profile=com.mojang.authlib.GameProfile@1d04df4d[id=00000000-0000-0000-0000-000000000047,name=|slot_81,properties={textures=[com.mojang.authlib.properties.Property@3c8386b0]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000000c, profile=com.mojang.authlib.GameProfile@658ab35b[id=00000000-0000-0000-0000-00000000000c,name=|slot_22,properties={textures=[com.mojang.authlib.properties.Property@7745dafa]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000020, profile=com.mojang.authlib.GameProfile@3c472318[id=00000000-0000-0000-0000-000000000020,name=|slot_42,properties={textures=[com.mojang.authlib.properties.Property@45e11683]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000034, profile=com.mojang.authlib.GameProfile@60fa8a88[id=00000000-0000-0000-0000-000000000034,name=|slot_62,properties={textures=[com.mojang.authlib.properties.Property@2200c31d]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000048, profile=com.mojang.authlib.GameProfile@5bbfdf6d[id=00000000-0000-0000-0000-000000000048,name=|slot_82,properties={textures=[com.mojang.authlib.properties.Property@37e3d2e6]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000000d, profile=com.mojang.authlib.GameProfile@6b9faf2a[id=00000000-0000-0000-0000-00000000000d,name=|slot_23,properties={textures=[com.mojang.authlib.properties.Property@3211fe09]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000021, profile=com.mojang.authlib.GameProfile@6e451ea2[id=00000000-0000-0000-0000-000000000021,name=|slot_43,properties={textures=[com.mojang.authlib.properties.Property@3da01042]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000035, profile=com.mojang.authlib.GameProfile@5adf6728[id=00000000-0000-0000-0000-000000000035,name=|slot_63,properties={textures=[com.mojang.authlib.properties.Property@7856850d]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000049, profile=com.mojang.authlib.GameProfile@7f3e8fa9[id=00000000-0000-0000-0000-000000000049,name=|slot_83,properties={textures=[com.mojang.authlib.properties.Property@3deaafce]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000000e, profile=com.mojang.authlib.GameProfile@694e999b[id=00000000-0000-0000-0000-00000000000e,name=|slot_24,properties={textures=[com.mojang.authlib.properties.Property@6211a686]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000022, profile=com.mojang.authlib.GameProfile@2f383a1e[id=00000000-0000-0000-0000-000000000022,name=|slot_44,properties={textures=[com.mojang.authlib.properties.Property@26d87c1e]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000036, profile=com.mojang.authlib.GameProfile@efffef6[id=00000000-0000-0000-0000-000000000036,name=|slot_64,properties={textures=[com.mojang.authlib.properties.Property@7e03cfee]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000004a, profile=com.mojang.authlib.GameProfile@5377b47[id=00000000-0000-0000-0000-00000000004a,name=|slot_84,properties={textures=[com.mojang.authlib.properties.Property@74e342b6]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000000f, profile=com.mojang.authlib.GameProfile@1828a83b[id=00000000-0000-0000-0000-00000000000f,name=|slot_25,properties={textures=[com.mojang.authlib.properties.Property@4e9a733a]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000023, profile=com.mojang.authlib.GameProfile@762e89ea[id=00000000-0000-0000-0000-000000000023,name=|slot_45,properties={textures=[com.mojang.authlib.properties.Property@467a994e]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000037, profile=com.mojang.authlib.GameProfile@7d7d197[id=00000000-0000-0000-0000-000000000037,name=|slot_65,properties={textures=[com.mojang.authlib.properties.Property@4054fc77]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000004b, profile=com.mojang.authlib.GameProfile@39047f69[id=00000000-0000-0000-0000-00000000004b,name=|slot_85,properties={textures=[com.mojang.authlib.properties.Property@6ee8287d]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000010, profile=com.mojang.authlib.GameProfile@64306102[id=00000000-0000-0000-0000-000000000010,name=|slot_26,properties={textures=[com.mojang.authlib.properties.Property@6474599]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000024, profile=com.mojang.authlib.GameProfile@66d3d5b7[id=00000000-0000-0000-0000-000000000024,name=|slot_46,properties={textures=[com.mojang.authlib.properties.Property@6d4f573]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000038, profile=com.mojang.authlib.GameProfile@5f31fb93[id=00000000-0000-0000-0000-000000000038,name=|slot_66,properties={textures=[com.mojang.authlib.properties.Property@669cb186]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000004c, profile=com.mojang.authlib.GameProfile@45d4382b[id=00000000-0000-0000-0000-00000000004c,name=|slot_86,properties={textures=[com.mojang.authlib.properties.Property@6ae002f3]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000011, profile=com.mojang.authlib.GameProfile@220b79e2[id=00000000-0000-0000-0000-000000000011,name=|slot_27,properties={textures=[com.mojang.authlib.properties.Property@695eba3e]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000025, profile=com.mojang.authlib.GameProfile@5a0d7e79[id=00000000-0000-0000-0000-000000000025,name=|slot_47,properties={textures=[com.mojang.authlib.properties.Property@380a7bfd]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000039, profile=com.mojang.authlib.GameProfile@a30ebc8[id=00000000-0000-0000-0000-000000000039,name=|slot_67,properties={textures=[com.mojang.authlib.properties.Property@27e4e6a0]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000004d, profile=com.mojang.authlib.GameProfile@6ec19fc5[id=00000000-0000-0000-0000-00000000004d,name=|slot_87,properties={textures=[com.mojang.authlib.properties.Property@264160e7]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000012, profile=com.mojang.authlib.GameProfile@17fc2f96[id=00000000-0000-0000-0000-000000000012,name=|slot_28,properties={textures=[com.mojang.authlib.properties.Property@24c06125]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000026, profile=com.mojang.authlib.GameProfile@26b365a6[id=00000000-0000-0000-0000-000000000026,name=|slot_48,properties={textures=[com.mojang.authlib.properties.Property@3d9970b5]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000003a, profile=com.mojang.authlib.GameProfile@2b50b413[id=00000000-0000-0000-0000-00000000003a,name=|slot_68,properties={textures=[com.mojang.authlib.properties.Property@345f39a7]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000004e, profile=com.mojang.authlib.GameProfile@498d390b[id=00000000-0000-0000-0000-00000000004e,name=|slot_88,properties={textures=[com.mojang.authlib.properties.Property@41243360]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000013, profile=com.mojang.authlib.GameProfile@3ffb3f33[id=00000000-0000-0000-0000-000000000013,name=|slot_29,properties={textures=[com.mojang.authlib.properties.Property@12898cf6]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000027, profile=com.mojang.authlib.GameProfile@258f33f[id=00000000-0000-0000-0000-000000000027,name=|slot_49,properties={textures=[com.mojang.authlib.properties.Property@32d71880]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000003b, profile=com.mojang.authlib.GameProfile@2c062f4b[id=00000000-0000-0000-0000-00000000003b,name=|slot_69,properties={textures=[com.mojang.authlib.properties.Property@3fb6047]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000004f, profile=com.mojang.authlib.GameProfile@ce31ea1[id=00000000-0000-0000-0000-00000000004f,name=|slot_89,properties={textures=[com.mojang.authlib.properties.Property@1f889b9e]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000014, profile=com.mojang.authlib.GameProfile@6a07baa9[id=00000000-0000-0000-0000-000000000014,name=|slot_30,properties={textures=[com.mojang.authlib.properties.Property@472b212c]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000028, profile=com.mojang.authlib.GameProfile@2f036ddd[id=00000000-0000-0000-0000-000000000028,name=|slot_50,properties={textures=[com.mojang.authlib.properties.Property@5b93bec]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-00000000003c, profile=com.mojang.authlib.GameProfile@32e26301[id=00000000-0000-0000-0000-00000000003c,name=|slot_70,properties={textures=[com.mojang.authlib.properties.Property@50dad63b]},legacy=false], listed=true, latency=1000, gameMode=SURVIVAL, displayName=empty[style={}], chatSession=null], b[profileId=00000000-0000-0000-0000-000000000050, profile=com.mojang.authlib.GameProfile@26e075ea[id=00000000-0000-0000-0000-000000000050,name=|slot_90,properties={textures=[com.mojang.authlib.properties.Property@72d6c960]},legacy=false], listed=true, latency=1000, gameMode=CREATIVE, displayName=literal{                     }[style={}], chatSession=null]]
  ]

[02:50:05] [Server thread/INFO]: player[/IP:PORT] logged in with entity id 1122 at ([spawn]-21.389370259247713, 53.0, -7.043843834096795)
```

**Comment by luizsusin** [comment]
I can confirm. I'm having the same error everytime someons logs in.
