### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mcdoeswhat** [libraryaddict/LibsDisguises#681]
```
[13:04:57 ERROR]: [LibsDisguises] Unhandled exception occurred in onPacketSending(PacketEvent) for LibsDisguises
java.util.NoSuchElementException: null
        at java.util.RegularEnumSet$EnumSetIterator.next(RegularEnumSet.java:103) ~[?:?]
        at java.util.RegularEnumSet$EnumSetIterator.next(RegularEnumSet.java:79) ~[?:?]
        at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerTabList.onPacketSending(PacketListenerTabList.java:53) ~[LibsDisguises (6).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib (16).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (16).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib (16).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib (16).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib (16).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib (16).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib (16).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (16).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (16).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2234) ~[?:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:300) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:585) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1594) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at java.lang.Thread.run(Thread.java:889) ~[?:?]
[13:04:57 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket@f32f48d4[
    a=[ADD_PLAYER, INITIALIZE_CHAT, UPDATE_GAME_MODE, UPDATE_LISTED, UPDATE_LATENCY, UPDATE_DISPLAY_NAME]
    b=[b[profileId=0a23d007-f814-38d6-a99a-fb57a814184a, profile=com.mojang.authlib.GameProfile@be724d4a[id=0a23d007-f814-38d6-a99a-fb57a814184a,name=ToDow,properties={textures=[com.mojang.authlib.properties.Property@b156b52e]},legacy=false], listed=true, latency=44, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=0c949608-9661-3e71-8f9f-5c483324de95, profile=com.mojang.authlib.GameProfile@fbe2a04f[id=0c949608-9661-3e71-8f9f-5c483324de95,name=LXR_,properties={textures=[com.mojang.authlib.properties.Property@1a8d7e17]},legacy=false], listed=true, latency=19, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=b6e9fc01-9fb2-3b35-b77c-32a48e3bc7cb, profile=com.mojang.authlib.GameProfile@2f72fb57[id=b6e9fc01-9fb2-3b35-b77c-32a48e3bc7cb,name=can_yue,properties={textures=[com.mojang.authlib.properties.Property@ec132db1]},legacy=false], listed=true, latency=31, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=f005d665-3732-38fe-8520-4e4265ab9da6, profile=com.mojang.authlib.GameProfile@acb7f5c1[id=f005d665-3732-38fe-8520-4e4265ab9da6,name=Albert,properties={textures=[com.mojang.authlib.properties.Property@4b06c7db]},legacy=false], listed=true, latency=45, gameMode=CREATIVE, displayName=null, chatSession=null], b[profileId=a582f7da-2f09-323a-83b9-357505ba07f7, profile=com.mojang.authlib.GameProfile@77dc46f2[id=a582f7da-2f09-323a-83b9-357505ba07f7,name=MQl,properties={textures=[com.mojang.authlib.properties.Property@3d2cb510]},legacy=false], listed=true, latency=28, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=197b7890-d6ee-3eac-8699-cb04f3fed130, profile=com.mojang.authlib.GameProfile@3886efed[id=197b7890-d6ee-3eac-8699-cb04f3fed130,name=genesis,properties={textures=[com.mojang.authlib.properties.Property@3f53d08d]},legacy=false], listed=true, latency=67, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=c2a6fbf1-66c1-3a21-95cd-80dfb80cc941, profile=com.mojang.authlib.GameProfile@3745b74b[id=c2a6fbf1-66c1-3a21-95cd-80dfb80cc941,name=zcj,properties={textures=[com.mojang.authlib.properties.Property@5db6536e]},legacy=false], listed=true, latency=1791, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=df4860f0-4796-3e88-92e5-e5363c93300b, profile=com.mojang.authlib.GameProfile@3b84dd94[id=df4860f0-4796-3e88-92e5-e5363c93300b,name=RuiZhi,properties={textures=[com.mojang.authlib.properties.Property@6103e2fa]},legacy=false], listed=true, latency=28, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=c3e4bddd-eb90-3dda-977a-fb13a2c498a1, profile=com.mojang.authlib.GameProfile@f2e8094[id=c3e4bddd-eb90-3dda-977a-fb13a2c498a1,name=Dear_huis,properties={textures=[com.mojang.authlib.properties.Property@3a8465dc]},legacy=false], listed=true, latency=15, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=0ff3a9f9-6516-37bb-97d5-1abd4aa6a1a3, profile=com.mojang.authlib.GameProfile@26d4041d[id=0ff3a9f9-6516-37bb-97d5-1abd4aa6a1a3,name=Felix,properties={textures=[com.mojang.authlib.properties.Property@9373c82f]},legacy=false], listed=true, latency=33, gameMode=SURVIVAL, displayName=null, chatSession=null], b[profileId=b9200377-5704-33ba-be6c-4fddc7d5e855, profile=com.mojang.authlib.GameProfile@4ad2763a[id=b9200377-5704-33ba-be6c-4fddc7d5e855,name=ImTime,properties={textures=[com.mojang.authlib.properties.Property@13ec7c83]},legacy=false], listed=true, latency=1, gameMode=SURVIVAL, displayName=null, chatSession=null]]
  ]
```
occurs when player joins the server
server version: git-Purpur-1876 (MC: 1.19.3)*
ProtocolLib version 5.0.0-SNAPSHOT-b608
LibsDisguises version 10.0.31-SNAPSHOT

**Comment by TheoRetisch1** [comment]
I have the same problem, the error occurs sometimes when a player joins the server.

Error: https://pastebin.com/CewG5J2Q
LibsDisguises version 10.0.31-SNAPSHOT
git-Paper-366  (MC: 1.19.3)
ProtocolLib version 5.0.0-SNAPSHOT-b608
