### ISSUE TITLE
HELP PLSSSSSSS

### ISSUE THREAD

**Issue by Wohaho** [libraryaddict/LibsDisguises#70]
[23:33:43] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to LibsDisguises v8.2.6-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.PlayerList.c(PlayerList.java:225) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.PlayerList.a(PlayerList.java:116) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.LoginListener.c(LoginListener.java:78) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.LoginListener.a(LoginListener.java:42) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:149) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
Caused by: java.lang.RuntimeException: Minecraft error.
	at com.comphenix.protocol.injector.PacketConstructor.createPacket(PacketConstructor.java:209) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:334) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:93) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:141) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at com.comphenix.protocol.injector.PacketConstructor.createPacket(PacketConstructor.java:199) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:334) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:93) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:141) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.2-50-gdce2b35-b3019jnks]
	... 14 more
Caused by: java.lang.NullPointerException

**Comment by NavidK0** [comment]
Outdated LibsDisguises, 8.2.6 is not supported if you use Spigot 1.8.3.
