### ISSUE TITLE
java.lang.IllegalStateException: Unable to read field value of protected final net.minecraft.network.syncher.DataWatcher net.minecraft.world.entity.Entity.am

### ISSUE THREAD

**Issue by SecretlyJealous** [libraryaddict/LibsDisguises#704]
This paper commit: https://github.com/PaperMC/paper/commit/29b17a892d11697dce9ee35d8eab593bb4748fb1 stops LibsDisguises from loading.

Here is the error:
```
[10:12:05 ERROR]: Error occurred while enabling LibsDisguises v10.0.32-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: Unable to read field value of protected final net.minecraft.network.syncher.DataWatcher net.minecraft.world.entity.Entity.am
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:28) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.getEntityWatcher(WrappedDataWatcher.java:553) ~[ProtocolLib.jar:?]
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.createNMSValues(ReflectionManager.java:2397) ~[LibsDisguises.jar:?]
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.registerValues(ReflectionManager.java:2235) ~[LibsDisguises.jar:?]
        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:255) ~[LibsDisguises.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-499]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at java.lang.invoke.DirectMethodHandle.checkBase(DirectMethodHandle.java:547) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:26) ~[ProtocolLib.jar:?]
        ... 16 more
```

**Comment by DrTheodor** [comment]
I have the same issue.

**Comment by LoJoSho** [comment]
It was reported to ProtocolLib already by LibraryAddict, https://github.com/dmulloy2/ProtocolLib/issues/2313
