### ISSUE TITLE
error on console

### ISSUE THREAD

**Issue by xsorencoolx** [libraryaddict/LibsDisguises#707]
hello i have problem when i used lasts portocolib and libsdiguise from jenkis my mythicmobs mobs wont show and i have to reload libsdiguse till it show and got these errors
27:49] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedRegistry
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.WrappedAttribute$Builder.build(WrappedAttribute.java:440)
[01:27:49] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.constructSpawnPackets(PacketHandlerSpawn.java:454)
[01:27:49] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.handle(PacketHandlerSpawn.java:78)
[01:27:49] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:79)
[01:27:49] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:54)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:551)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:525)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.processQueue(NetworkManager.java:382)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.p(NetworkManager.java:355)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacketQueue(NetworkManager.java:349)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:263)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1903)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1876)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.a(EntityTrackerEntry.java:313)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:297)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:2495)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayers(PlayerChunkMap.java:2392)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2105)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.g(PlayerChunkMap.java:2126)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:891)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[01:27:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[01:27:49] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedRegistry
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.WrappedAttribute$Builder.build(WrappedAttribute.java:440)
[01:27:49] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerAttributes.handle(PacketHandlerAttributes.java:75)
[01:27:49] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:79)
[01:27:49] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:54)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:551)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:525)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[01:27:49] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:243)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1903)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1876)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.a(EntityTrackerEntry.java:330)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:297)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:2495)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayers(PlayerChunkMap.java:2392)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2105)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.g(PlayerChunkMap.java:2126)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:891)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[01:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[01:27:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[01:27:50] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedRegistry
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.WrappedAttribute$Builder.build(WrappedAttribute.java:440)
[01:27:50] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.constructSpawnPackets(PacketHandlerSpawn.java:454)
[01:27:50] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerSpawn.handle(PacketHandlerSpawn.java:78)
[01:27:50] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:79)
[01:27:50] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:54)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:551)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:525)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.processQueue(NetworkManager.java:382)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.p(NetworkManager.java:355)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacketQueue(NetworkManager.java:349)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:263)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1903)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1876)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.a(EntityTrackerEntry.java:313)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:297)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:2495)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayers(PlayerChunkMap.java:2392)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2105)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.g(PlayerChunkMap.java:2126)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:891)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[01:27:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[01:27:50] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedRegistry
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.WrappedAttribute$Builder.build(WrappedAttribute.java:440)
[01:27:50] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerAttributes.handle(PacketHandlerAttributes.java:75)
[01:27:50] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:79)
[01:27:50] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerMain.onPacketSending(PacketListenerMain.java:54)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:551)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:525)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[01:27:50] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:243)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1903)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1876)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.a(EntityTrackerEntry.java:330)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:297)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:2495)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayers(PlayerChunkMap.java:2392)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2105)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerChunkMap.g(PlayerChunkMap.java:2126)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:891)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[01:27:50] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[01:27:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by libraryaddict** [comment]
Can you upload the contents of latest.log in your logs folder into pastebin, then post that link here. I'd like the full startup log thank you.

**Comment by libraryaddict** [comment]
That log is not public

**Comment by libraryaddict** [comment]
Alright, ignoring the pirated plugins you are running. You are not on the latest protocol lib
