### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAlignment

### ISSUE THREAD

**Issue by DexterSK** [libraryaddict/LibsDisguises#711]
[08:51:16 INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.33
[08:51:16 INFO]: [LibsDisguises] File Name: LibsDisguises-10.0.33-Github.jar
[08:51:16 INFO]: [LibsDisguises] Discovered nms version: v1_19_R3 (v1_19_R3)
[08:51:16 INFO]: [LibsDisguises] Jenkins Build: #1188
[08:51:16 INFO]: [LibsDisguises] Build Date: 25/04/2023 05:11
[08:51:16 WARN]: [LibsDisguises] If you own the plugin, place the premium jar downloaded from https://www.spigotmc.org/resources/libs-disguises.32453/ in plugins/LibsDisguises/
[08:51:16 INFO]: [LibsDisguises] You are running the free version, commands limited to non-players and operators. (Console, Command Blocks, Admins)
[08:51:38 WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAlignment
[08:51:38 WARN]:        at LibsDisguises-10.0.33-Github.jar//me.libraryaddict.disguise.utilities.params.ParamInfoTypes.getParamInfos(ParamInfoTypes.java:150)
[08:51:38 WARN]:        at LibsDisguises-10.0.33-Github.jar//me.libraryaddict.disguise.utilities.params.ParamInfoManager.<clinit>(ParamInfoManager.java:100)
[08:51:38 WARN]:        at LibsDisguises-10.0.33-Github.jar//me.libraryaddict.disguise.utilities.parser.DisguiseParser.createDefaultMethods(DisguiseParser.java:69)
[08:51:38 WARN]:        at LibsDisguises-10.0.33-Github.jar//me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:257)
[08:51:38 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[08:51:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[08:51:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[08:51:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[08:51:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569)
[08:51:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480)
[08:51:38 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643)
[08:51:38 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442)
[08:51:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:344)
[08:51:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1120)
[08:51:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[08:51:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[08:51:38 WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAlignment
[08:51:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185)
[08:51:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152)
[08:51:38 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08:51:38 WARN]:        ... 16 more
[08:51:38 ERROR]: Error occurred while enabling LibsDisguises v10.0.33 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.libraryaddict.disguise.utilities.params.ParamInfoManager
        at me.libraryaddict.disguise.utilities.parser.constructors.TextDisplayParam.<init>(TextDisplayParam.java:14) ~[LibsDisguises-10.0.33-Github.jar:?]
        at me.libraryaddict.disguise.utilities.parser.DisguiseParser.createDefaultMethods(DisguiseParser.java:180) ~[LibsDisguises-10.0.33-Github.jar:?]
        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:257) ~[LibsDisguises-10.0.33-Github.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:51:38 INFO]: [LibsDisguises] Disabling LibsDisguises v10.0.33

**Comment by libraryaddict** [comment]
You need to update paper to the latest 1.19.4 build
