### ISSUE TITLE
Getting constantly kicked

### ISSUE THREAD

**Issue by DontSharee** [libraryaddict/LibsDisguises#718]
[22:46:51 INFO]: [Skript] No matching static constructor: IntArrayList.<init> called with ([] (Object[]))
[22:46:51 ERROR]: [LibsDisguises] Unhandled exception occurred in onPacketSending(PacketEvent) for LibsDisguises
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "entityIds" is null
        at me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerEntityDestroy.onPacketSending(PacketListenerEntityDestroy.java:42) ~[LibsDisguises-10.0.35-Free.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:528) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:566) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib 1.19.4.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:287) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:184) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:157) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:152) ~[ProtocolLib 1.19.4.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.invoke(ExprJavaCall.java:486) ~[skript-reflect.jar:?]
        at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.getSingle(ExprJavaCall.java:228) ~[skript-reflect.jar:?]
        at com.btk5h.skriptmirror.skript.CondExpressionStatement.check(CondExpressionStatement.java:38) ~[skript-reflect.jar:?]
        at ch.njol.skript.lang.Condition.run(Condition.java:54) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript-2.6.4.jar:?]
        at com.btk5h.skriptmirror.skript.CondExpressionStatement.walk(CondExpressionStatement.java:66) ~[skript-reflect.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[Skript-2.6.4.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at ch.njol.skript.Skript.dispatchCommand(Skript.java:1454) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:82) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.effects.Delay$1.run(Delay.java:109) ~[Skript-2.6.4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:46:51 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy@3f71c393[
    a=<null>
  ]

[22:46:51 ERROR]: Packet encoding of packet ID 58 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntList.size()" because "list" is null
        at net.minecraft.network.FriendlyByteBuf.writeIntIdList(FriendlyByteBuf.java:238) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundRemoveEntitiesPacket.write(ClientboundRemoveEntitiesPacket.java:25) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.19.3.jar:git-Paper-448]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at me.doclic.noencryption.PlayerListener$1.write(PlayerListener.java:28) ~[NoEncryption-1.19.3-4.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at me.MrGraycat.eGlow.Util.Packets.PipelineInjector$1.write(PipelineInjector.java:92) ~[eGlow 3.2.3 1.9.4-1.19.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:112) ~[TAB_v4.0.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib 1.19.4.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib 1.19.4.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib 1.19.4.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:46:51 INFO]: DontShare lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntList.size()" because "list" is null

**Comment by libraryaddict** [comment]
Please share the contents of `/ld logs`

**Comment by DontSharee** [comment]
My log file: https://pastebin.com/2QeRV76L, my combined config files: https://pastebin.com/9ChcGCgB and my disguises file: https://pastebin.com/08XGWD94

**Comment by libraryaddict** [comment]
Weird, try installing the last ProtocolLib released

https://www.spigotmc.org/resources/protocollib.1997/

**Comment by DontSharee** [comment]
Alriught ill try thanks

**Comment by DontSharee** [comment]
[02:14:44 INFO]: [Skript] No matching static constructor: IntArrayList.<init> called with ([] (Object[]))
[02:14:44 ERROR]: [LibsDisguises] Unhandled exception occurred in onPacketSending(PacketEvent) for LibsDisguises
java.lang.NullPointerException: null
[02:14:44 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy@2e36863c[
    a=<null>
  ]

[02:14:44 ERROR]: Packet encoding of packet ID 58 threw (skippable? false)
java.lang.NullPointerException: null
[02:14:44 INFO]: DontShare lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

**Comment by libraryaddict** [comment]
What are you doing in your skript? You might be constructing a destroy packet incorrectly.
Although it is a bug in Lib's Disguises, it's only a bug because it seems like the packet is malformed

**Comment by DontSharee** [comment]
function plot_spawnNPC(p: player):

	loop {-plot::%{_p}%::stands::*}:
		kill loop-value
	delete {-plot::%{_p}%::stands::*}

	set {_loc} to {-plot::%{_p}%::location} ~ vector(-18,1,5)
	set yaw of {_loc} to -90
	set {_disguise} to disguise from "Bwendenn"
	set burning of {_disguise} to false
	set head pose of {_disguise} to vector(90, 0, 0)
	set body pose of {_disguise} to vector(90, 0, 0)
	set custom name visibility of disguise {_disguise} to false
	set glowing of disguise {_disguise} to true
	set glowing color of disguise {_disguise} to aqua
	spawn armor stand at {_loc}
	set {-plot::%{_p}%::stands::1} to last spawned armor stand
	{-plot::%{_p}%::stands::1}.setInvulnerable(true)
	{-plot::%{_p}%::stands::1}.setInvisible(false)
	{-plot::%{_p}%::stands::1}.setGravity(false)
	set tag "custom;Plot" of nbt compound of {-plot::%{_p}%::stands::1} to {_p}'s uuid
	disguise {-plot::%{_p}%::stands::1} as {_disguise}
	
	Thats what I'm doing in skript.
	I figured out its whenever I run /spawn which basically just deletes the armor stand. It sends this 
	
	[02:41:08 INFO]: [Skript] No matching static constructor: IntArrayList.<init> called with ([] (Object[]))
[02:41:08 ERROR]: [LibsDisguises] Unhandled exception occurred in onPacketSending(PacketEvent) for LibsDisguises
java.lang.NullPointerException: null
[02:41:08 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy@252a223c[
    a=<null>
  ]

[02:41:08 ERROR]: Packet encoding of packet ID 58 threw (skippable? false)
