### ISSUE TITLE
1.20.2 not supported

### ISSUE THREAD

**Issue by DarktisDH** [libraryaddict/LibsDisguises#727]
Hello, I have a problem while loading the plugin.

Version PaperMC 1.20.2

I would appreciate any help.
Thank you in advance :-)

Stack trace :

[12:22:59 ERROR]: Error occurred while enabling LibsDisguises v10.0.37 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R1/inventory/CraftItemStack
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:375) ~[?:?]
at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getReflectionManager(ReflectionManager.java:818) ~[LibsDisguises.jar:?]
at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:206) ~[LibsDisguises.jar:?]
at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:253) ~[LibsDisguises.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-197]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-197]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-197]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-197]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-197]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-197]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-197]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-197]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-197]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R1.inventory.CraftItemStack
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 17 more
[12:22:59 INFO]: [LibsDisguises] Disabling LibsDisguises v10.0.37

**Comment by libraryaddict** [comment]
What server software are you using? Spigot? CraftBukkit?

**Comment by DarktisDH** [comment]
This server is running Paper version git-Paper-197 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: e284bb1)

**Comment by DarktisDH** [comment]
Is it caused probably by bad version ?

**Comment by libraryaddict** [comment]
Maybe, I'll have to check 1.20.2 when I can

**Comment by DarktisDH** [comment]
Ok, thank you

**Comment by DarktisDH** [comment]
Is it worth it to downgrade the server to 1.20 ? I thought it could break a lot of things on the server but we really want this plugin :D.

**Comment by libraryaddict** [comment]
Oh forgot to update this issue.

I was unprepared for the 1.20.2 drop, and I won't have an update ready for the next 24h I believe. Still have some work to go.

**Comment by DarktisDH** [comment]
Np :) , thank you for your work. I am looking forward for update.

**Comment by libraryaddict** [comment]
Alright, so once things are done; the latest build at https://ci.md-5.net/job/LibsDisguises/ would work.
However it isn't available yet as some backend stuff needs to be updated. I'm not sure how long that'll take. Could be under a day to a week.

**Comment by DarktisDH** [comment]
Okay, thank you.

**Comment by andrewkm** [comment]
> Alright, so once things are done; the latest build at https://ci.md-5.net/job/LibsDisguises/ would work. However it isn't available yet as some backend stuff needs to be updated. I'm not sure how long that'll take. Could be under a day to a week.

Many thanks! <3
Was just about to report my startup as well lol:

```
[17:20:21] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.37-SNAPSHOT
[17:20:21] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[17:20:21] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_20_R2 (v1_20)
[17:20:21] [Server thread/INFO]: [LibsDisguises] Jenkins Build: unknown
[17:20:21] [Server thread/INFO]: [LibsDisguises] Build Date: 26/09/2023 04:38
[17:20:21] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v10.0.37, build #1239, created 25/06/2023 07:08)
[17:20:21] [Server thread/INFO]: [LibsDisguises] Registered to: 2 (2)
[17:20:21] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[17:20:21] [Server thread/INFO]: Error occurred while enabling LibsDisguises v10.0.37-SNAPSHOT (Is it up to date?)
[17:20:21] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R1/inventory/CraftItemStack
[17:20:21] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[17:20:21] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:421)
[17:20:21] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:412)
[17:20:21] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getReflectionManager(ReflectionManager.java:818)
[17:20:21] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:206)
[17:20:21] [Server thread/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:253)
[17:20:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[17:20:21] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[17:20:21] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[17:20:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[17:20:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644)
[17:20:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555)
[17:20:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
[17:20:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[17:20:21] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[17:20:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
[17:20:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[17:20:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[17:20:21] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R1.inventory.CraftItemStack
[17:20:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[17:20:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[17:20:21] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[17:20:21] [Server thread/WARN]: 	... 18 more
[17:20:21] [Server thread/INFO]: [LibsDisguises] Disabling LibsDisguises v10.0.37-SNAPSHOT
```

**Comment by andrewkm** [comment]
@libraryaddict I should mention, I am testing the version compiled against:
https://github.com/libraryaddict/LibsDisguises/commit/2cb01ddc7537d3ab4238e6e739773b7f0dfcc4af

Which is after your 1.20.2 update. (?)

**Comment by libraryaddict** [comment]
> @libraryaddict I should mention, I am testing the version compiled against: [2cb01dd](https://github.com/libraryaddict/LibsDisguises/commit/2cb01ddc7537d3ab4238e6e739773b7f0dfcc4af)
> 
> Which is after your 1.20.2 update. (?) Paper 1.20.2 Build 207. Let me know if you need more information. PS Build log: https://pastebin.com/raw/T3WeRPZk

Jenkins isn't building atm

**Comment by andrewkm** [comment]
> > @libraryaddict I should mention, I am testing the version compiled against: [2cb01dd](https://github.com/libraryaddict/LibsDisguises/commit/2cb01ddc7537d3ab4238e6e739773b7f0dfcc4af)
> > Which is after your 1.20.2 update. (?) Paper 1.20.2 Build 207. Let me know if you need more information. PS Build log: https://pastebin.com/raw/T3WeRPZk
> 
> Jenkins isn't building atm

I'm saying I built it on mine, and the latest commit doesn't function on 1.20.2

**Comment by libraryaddict** [comment]
> > > @libraryaddict I should mention, I am testing the version compiled against: [2cb01dd](https://github.com/libraryaddict/LibsDisguises/commit/2cb01ddc7537d3ab4238e6e739773b7f0dfcc4af)
> > > Which is after your 1.20.2 update. (?) Paper 1.20.2 Build 207. Let me know if you need more information. PS Build log: https://pastebin.com/raw/T3WeRPZk
> > 
> > 
> > Jenkins isn't building atm
> 
> I'm saying I built it on mine, and the latest commit doesn't function on 1.20.2 Meaning this change: [2cb01dd](https://github.com/libraryaddict/LibsDisguises/commit/2cb01ddc7537d3ab4238e6e739773b7f0dfcc4af) doesn't add 1.20.2 functionality as it's still not loading the plugin.

That's incorrect, you posted a log that shows it loading v1_20 which is no longer a nms version enum

**Comment by andrewkm** [comment]
> > > > @libraryaddict I should mention, I am testing the version compiled against: [2cb01dd](https://github.com/libraryaddict/LibsDisguises/commit/2cb01ddc7537d3ab4238e6e739773b7f0dfcc4af)
> > > > Which is after your 1.20.2 update. (?) Paper 1.20.2 Build 207. Let me know if you need more information. PS Build log: https://pastebin.com/raw/T3WeRPZk
> > > 
> > > 
> > > Jenkins isn't building atm
> > 
> > 
> > I'm saying I built it on mine, and the latest commit doesn't function on 1.20.2 Meaning this change: [2cb01dd](https://github.com/libraryaddict/LibsDisguises/commit/2cb01ddc7537d3ab4238e6e739773b7f0dfcc4af) doesn't add 1.20.2 functionality as it's still not loading the plugin.
> 
> That's incorrect, you posted a log that shows it loading v1_20 which is no longer a nms version enum

Ok, yeah, I blame Jenkin's "Last Successful Artifacts" cache.

```
[18:11:27] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.37-SNAPSHOT
[18:11:27] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[18:11:27] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_20_R2 (v1_20_R2)
[18:11:27] [Server thread/INFO]: [LibsDisguises] Jenkins Build: unknown
[18:11:27] [Server thread/INFO]: [LibsDisguises] Build Date: 01/10/2023 22:09
[18:11:27] [Server thread/INFO]: [LibsDisguises] Found a premium Lib's Disguises jar (v10.0.37, build #1239, created 25/06/2023 07:08)
[18:11:27] [Server thread/INFO]: [LibsDisguises] Registered to: 2 (2)
[18:11:27] [Server thread/INFO]: [LibsDisguises] Premium enabled, thank you for supporting Lib's Disguises!
[18:11:31] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[18:11:31] [Server thread/INFO]: [LibsDisguises] Loaded 1 custom disguise
[18:11:31] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[18:11:31] [Server thread/INFO]: [LibsDisguises] The author sees Metrics disabled, the author is sad
```

**Comment by libraryaddict** [comment]
Latest build now works.
