### ISSUE TITLE
PacketEvents SoundCategory.PLAYER not found

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [libraryaddict/LibsDisguises#757]
Hi,
I'm testing your 0.4.1 PacketEvents version and encountered this error on 1.20.6 version

```
[06:57:57] [Netty Epoll Server IO #1/WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IllegalArgumentException: No enum constant com.github.retrooper.packetevents.protocol.sound.SoundCategory.PLAYERS
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at org.bukkit.craftbukkit.legacy.FieldRename.valueOf(FieldRename.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/com.github.retrooper.packetevents.protocol.sound.SoundCategory.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_legacy_FieldRename_valueOf(SoundCategory.java) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/com.github.retrooper.packetevents.protocol.sound.SoundCategory.valueOf(SoundCategory.java:21) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at LibsDisguises-0.4.1-PacketEvents.jar/me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerSounds.onPacketPlaySend(PacketListenerSounds.java:181) ~[LibsDisguises-0.4.1-PacketEvents.jar:?]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/com.github.retrooper.packetevents.event.SimplePacketListenerAbstract.onPacketSend(SimplePacketListenerAbstract.java:64) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at packetevents-spigot-2.3.1-SNAPSHOT.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[packetevents-spigot-2.3.1-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection$2.write(Connection.java:759) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]

```

**Comment by libraryaddict** [comment]
Fixed in next build when that's there
