### ISSUE TITLE
Grid Lock Desync

### ISSUE THREAD

**Issue by JasonHorkles** [libraryaddict/LibsDisguises#771]
On Paper 1.21.1-40, LD 10.0.44-SNAPSHOT with PE 2.5.0+ebe73587f-SNAPSHOT, the grid locking doesn't seem to work properly at all. Over time, the player becomes totally desynced from the falling block and it doesn't update until they jump. It's easiest to reproduce the issue while crouching and moving around. I can get a video if necessary

**Comment by JasonHorkles** [comment]
Just noticed that this issue also throws a bunch of warnings in console when you jump with the disguise active:
```
[16:04:19 WARN]: java.lang.IllegalStateException: Unknown packet class com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityPositionSync
[16:04:19 WARN]:        at LibsDisguises.jar//me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerMovement.handleMovement(PacketHandlerMovement.java:102)
[16:04:19 WARN]:        at LibsDisguises.jar//me.libraryaddict.disguise.utilities.packets.packethandlers.PacketHandlerMovement.handle(PacketHandlerMovement.java:50)
[16:04:19 WARN]:        at LibsDisguises.jar//me.libraryaddict.disguise.utilities.packets.PacketsHandler.transformPacket(PacketsHandler.java:94)
[16:04:19 WARN]:        at LibsDisguises.jar//me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerViewSelfDisguise.onPacketPlaySend(PacketListenerViewSelfDisguise.java:89)
[16:04:19 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.event.SimplePacketListenerAbstract.onPacketSend(SimplePacketListenerAbstract.java:64)
[16:04:19 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51)
[16:04:19 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84)
[16:04:19 WARN]:        at packetevents-spigot-2.7.0.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:61)
[16:04:19 WARN]:        at packetevents-spigot-2.7.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:88)
[16:04:19 WARN]:        at packetevents-spigot-2.7.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:73)
[16:04:19 WARN]:        at packetevents-spigot-2.7.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:52)
[16:04:19 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[16:04:19 WARN]:        at packetevents-spigot-2.7.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:107)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
[16:04:19 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
[16:04:19 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
[16:04:19 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[16:04:19 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:728)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:863)
[16:04:19 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:959)
[16:04:19 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:295)
[16:04:19 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:492)
[16:04:19 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:479)
[16:04:19 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[16:04:19 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[16:04:19 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[16:04:19 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[16:04:19 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:04:19 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:04:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by libraryaddict** [comment]
There shouldn't be an issue anymore in grid locks as of the latest builds, also added block display support for grid lock.
Mind checking if you are still experiencing any issues?

**Comment by JasonHorkles** [comment]
So far that works great! I did notice, however, that punching a falling block disguise throws `java.lang.NullPointerException` in console due to it not having a sound to play
https://pastes.dev/duJCOTIlSp

**Comment by libraryaddict** [comment]
Fixed

**Comment by JasonHorkles** [comment]
Thank you! ❤
