### ISSUE TITLE
IndexOutOfBoundsException occurs on join

### ISSUE THREAD

**Issue by MrMaleficus** [libraryaddict/LibsDisguises#781]
Latest on paper 1.21.3, LibsDisguises, and packet-events

```
[14:05:48] [Netty Epoll Server IO #2/WARN]: java.lang.IndexOutOfBoundsException: readerIndex(17) + length(1) exceeds writerIndex(17): PooledUnsafeDirectByteBuf(ridx: 17, widx: 17, cap: 256)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readByte(PacketWrapper.java:354)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readVarInt(PacketWrapper.java:394)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readEntityMetadata(PacketWrapper.java:965)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.read(WrapperPlayServerEntityMetadata.java:52)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:277)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:182)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:172)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.<init>(WrapperPlayServerEntityMetadata.java:36)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.utilities.DisguiseUtilities.constructWrapper(DisguiseUtilities.java:3051)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at LibsDisguises.jar//me.libraryaddict.disguise.utilities.packets.packetlisteners.PacketListenerViewSelfDisguise.onPacketPlaySend(PacketListenerViewSelfDisguise.java:60)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.event.SimplePacketListenerAbstract.onPacketSend(SimplePacketListenerAbstract.java:64)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:84)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:61)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:88)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:73)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:52)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[14:05:48] [Netty Epoll Server IO #2/WARN]: 	at packetevents-spigot-2.6.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:107)
```

**Comment by libraryaddict** [comment]
Try updating PacketEvents to the latest snapshot build. You can do this ingame by `/ld pe snapshots`
Can I get your full server startup log? And do you know what disguise its trying to send?

**Comment by DonPedroTV** [comment]
I tested on the version Libs Disguises 10.0.44 and tested on the latest build - 1488 

I posted the logs that weighed less. Because the ones with another version of Libs Disgusises weighed 15 GB
