### ISSUE TITLE
Error when enabling LibsDisguises on 1.16.5

### ISSUE THREAD

**Issue by TUCAOEVER** [libraryaddict/LibsDisguises#784]
```
[15:33:24 WARN]: java.lang.NoClassDefFoundError: Could not initialize class me.libraryaddict.disguise.disguisetypes.MetaIndex
[15:33:24 WARN]:        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.createNMSValues(ReflectionManager.java:2571)
[15:33:24 WARN]:        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.registerValues(ReflectionManager.java:2404)
[15:33:24 WARN]:        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:292)
[15:33:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:33:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:33:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[15:33:24 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[15:33:24 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[15:33:24 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596)
[15:33:24 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309)
[15:33:24 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[15:33:24 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[15:33:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:33:24 WARN]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException: Cannot find ParticleType class (MojMap: false) [in thread "Server thread"]
[15:33:24 WARN]:        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
[15:33:24 WARN]:        at com.comphenix.protocol.wrappers.WrappedParticle.ensureMethods(WrappedParticle.java:39)
[15:33:24 WARN]:        at com.comphenix.protocol.wrappers.WrappedParticle.create(WrappedParticle.java:274)
[15:33:24 WARN]:        at me.libraryaddict.disguise.disguisetypes.MetaIndex.<clinit>(MetaIndex.java:164)
[15:33:24 WARN]:        ... 13 more
[15:33:24 ERROR]: Error occurred while enabling LibsDisguises v10.0.44 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.libraryaddict.disguise.disguisetypes.MetaIndex
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.createNMSValues(ReflectionManager.java:2571) ~[?:?]
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.registerValues(ReflectionManager.java:2404) ~[?:?]
        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:292) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException: Cannot find ParticleType class (MojMap: false) [in thread "Server thread"]
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.comphenix.protocol.wrappers.WrappedParticle.ensureMethods(WrappedParticle.java:39) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedParticle.create(WrappedParticle.java:274) ~[?:?]
        at me.libraryaddict.disguise.disguisetypes.MetaIndex.<clinit>(MetaIndex.java:164) ~[?:?]
        ... 13 more
```
Log when starting server.  Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by libraryaddict** [comment]
To be clear, this is a bug in https://github.com/retrooper/packetevents

**Comment by ItsIgnacioPortal** [comment]
This is still happening on v10.0.44 of LibsDisguises

**Comment by libraryaddict** [comment]
> This is still happening on v10.0.44 of LibsDisguises

Update to dev builds
