### ISSUE TITLE
LibsDisguise HashSet Class Exception Errors

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#92]
@NavidK0 Have some unique errors occur when people try to disguise into various mobs and undisguise.

LibsDisguise dev 53.
http://server.psmc.ca:8080/job/LibsDisguises/53/

```
[15:59:23] [Server thread/INFO]: mibby issued server command: /disguise cow
[15:59:23] [Server thread/INFO]: java.lang.ClassCastException: java.util.HashMap$KeySet cannot be cast to java.util.HashSet
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:739)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.startDisguise(Disguise.java:753)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.disguiseEntity(DisguiseAPI.java:163)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.disguiseToAll(DisguiseAPI.java:234)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:47)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:59:23] [Server thread/INFO]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:59:23] [Server thread/INFO]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[15:59:23] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
[15:59:23] [Server thread/INFO]: java.lang.ClassCastException: java.util.HashMap$KeySet cannot be cast to java.util.HashSet
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:858)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:995)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:758)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:780)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[15:59:23] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
```

```
[15:59:23] [Server thread/INFO]: mibby issued server command: /dis spider
[15:59:23] [Server thread/INFO]: java.lang.ClassCastException: java.util.HashMap$KeySet cannot be cast to java.util.HashSet
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:739)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.startDisguise(Disguise.java:753)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.disguiseEntity(DisguiseAPI.java:163)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.disguiseToAll(DisguiseAPI.java:234)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:47)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:59:23] [Server thread/INFO]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:59:23] [Server thread/INFO]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[15:59:23] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
[15:59:23] [Server thread/INFO]: java.lang.ClassCastException: java.util.HashMap$KeySet cannot be cast to java.util.HashSet
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:858)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:995)
[15:59:23] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:758)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:59:23] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:780)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[15:59:23] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[15:59:23] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
```

```
[16:04:21] [Server thread/INFO]: mibby issued server command: /undis
[16:04:21] [Server thread/INFO]: java.lang.ClassCastException: java.util.HashMap$KeySet cannot be cast to java.util.HashSet
[16:04:21] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.removeSelfDisguise(DisguiseUtilities.java:808)
[16:04:21] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:466)
[16:04:21] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:376)
[16:04:21] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.UndisguiseCommand.onCommand(UndisguiseCommand.java:22)
[16:04:21] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:04:21] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:04:21] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:04:21] [Server thread/INFO]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:04:21] [Server thread/INFO]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[16:04:21] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
[16:04:21] [Server thread/INFO]: java.lang.ClassCastException: java.util.HashMap$KeySet cannot be cast to java.util.HashSet
[16:04:21] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:739)
[16:04:21] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:471)
[16:04:21] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:376)
[16:04:21] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.UndisguiseCommand.onCommand(UndisguiseCommand.java:22)
[16:04:21] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:04:21] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:04:21] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:04:21] [Server thread/INFO]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:04:21] [Server thread/INFO]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[16:04:21] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[16:04:21] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NavidK0** [comment]
May I ask which version of Spigot you're using? This issue came up randomly with one other person.

**Comment by vst8800** [comment]
We have the same errors. They started after the last three commits/changes to PaperSpigot. We are using latest PaperSpigot 1.8.8.

**Comment by mibby** [comment]
I am using PaperSpigot git-PaperSpigot-5063a06-d3e0b6f (MC: 1.8.8). Could it be a problem with one of the latest 3 commits from build 371/372?

https://ci.destroystokyo.com/job/PaperSpigot/changes

**Comment by Zbob750** [comment]
Users of PaperSpigot and SportBukkit are affected.
It was broken by this commit, https://hub.spigotmc.org/stash/projects/PAPER/repos/paperspigot/commits/0265f4eaef9f1d2012155250576825febca4a639

Which we pulled from SportBukkit here, https://github.com/OvercastNetwork/SportBukkit/commit/3005a20c5c31fa89e169bd1fae9c6f93f34e1945

Which broke it because ```trackedPlayers``` no longer returns a HashSet. Haven't had a ton of time to look into this just yet.

**Comment by NavidK0** [comment]
Alright, thanks. I myself don't use PaperSpigot, but I should be able to do some testing later today amd release a hotfix.

**Comment by NavidK0** [comment]
It caused a bit of a problem, since Spigot/Bukkit uses HashSets and PaperSpigot/SportsBukkit use HashMaps, and they're two different classes and both don't extend Collection.

**Comment by NavidK0** [comment]
Fixed with https://github.com/libraryaddict/LibsDisguises/commit/e7a5d0763f36660d46de093c99389b2796dc3e8e

**Comment by mibby** [comment]
Thanks for the fix @NavidK0 !

**Comment by Zbob750** [comment]
:+1:

**Comment by vst8800** [comment]
Thanks, those errors are fixed, now new ones: http://pastebin.com/ipfkBVdL
