### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#93]
@NavidK0 

PaperSpigot git-PaperSpigot-a55011e-d3e0b6f (MC: 1.8.8)
LibsDisguise dev 54

```
[14:49:55] [Server thread/INFO]: mibby issued server command: /dis zombie
[14:49:55] [Server thread/INFO]: java.util.ConcurrentModificationException
[14:49:55] [Server thread/INFO]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
[14:49:55] [Server thread/INFO]: 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
[14:49:55] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:754)
[14:49:55] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.startDisguise(Disguise.java:753)
[14:49:55] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.disguiseEntity(DisguiseAPI.java:163)
[14:49:55] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.disguiseToAll(DisguiseAPI.java:234)
[14:49:55] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.DisguiseCommand.onCommand(DisguiseCommand.java:47)
[14:49:55] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:49:55] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:49:55] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[14:49:55] [Server thread/INFO]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:49:55] [Server thread/INFO]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[14:49:55] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[14:49:55] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
```
```
[14:50:38] [Server thread/INFO]: mibby issued server command: /undis
[14:50:38] [Server thread/INFO]: java.util.ConcurrentModificationException
[14:50:38] [Server thread/INFO]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
[14:50:38] [Server thread/INFO]: 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
[14:50:38] [Server thread/INFO]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:754)
[14:50:38] [Server thread/INFO]: 	at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:471)
[14:50:38] [Server thread/INFO]: 	at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:376)
[14:50:38] [Server thread/INFO]: 	at me.libraryaddict.disguise.commands.UndisguiseCommand.onCommand(UndisguiseCommand.java:22)
[14:50:38] [Server thread/INFO]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:50:38] [Server thread/INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:50:38] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[14:50:38] [Server thread/INFO]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:50:38] [Server thread/INFO]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[14:50:38] [Server thread/INFO]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[14:50:38] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NavidK0** [comment]
Should be fixed with https://github.com/libraryaddict/LibsDisguises/commit/66ab7ac3efdc67cb5e372b9635bd7469756d0ffa
