### ISSUE TITLE
LibsDisguise 1.9 Support

### ISSUE THREAD

**Issue by mibby** [libraryaddict/LibsDisguises#96]
Using LibsDisguise 1.9 dev 3 with ProtocoLib dev 232 http://ci.dmulloy2.net/job/ProtocolLib/232/

Is LibsDisguise all set to work with 1.9, just need to wait for ProtocolLib?

**Comment by NavidK0** [comment]
I'm not quite sure how it'll react quite yet. I first need the ProtocolLib 1.9 build before I can actually do anything. LibsDisguises manipulates the datawatcher, which has definitely changed in 1.9, so I need to accommodate that.

**Comment by mibby** [comment]
Roger that. I'll keep an eye on ProtocolLib then. :)

Some more errors but probably all irrelevant until ProtocolLib officially supports 1.9.

```
[16:03:04] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to LibsDisguises v9.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:815) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.IllegalArgumentException: Could not find a packet by the type UNREGISTERED[PLAY, SERVER, 38, legacy: 56, classNames: [PacketPlayOutMapChunkBulk]]
	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:168) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:952) ~[?:?]
	at me.libraryaddict.disguise.utilities.DisguiseUtilities.getBedChunkPacket(DisguiseUtilities.java:333) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.chunkMove(DisguiseListener.java:108) ~[?:?]
	at me.libraryaddict.disguise.DisguiseListener.onJoin(DisguiseListener.java:156) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	... 14 more
```
```
[16:03:04] [Server thread/ERROR]: [LibsDisguises] Unhandled exception occured in onPacketSending(PacketEvent) for LibsDisguises
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:699) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:678) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:146) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at me.libraryaddict.disguise.utilities.PacketsManager$5.onPacketSending(PacketsManager.java:1195) ~[LibsDisguises.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:318) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:401) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:82) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.handleScheduled(NettyChannelInjector.java:367) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.onMessageScheduled(NettyChannelInjector.java:335) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:193) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.NetworkManager.sendPacket(NetworkManager.java:142) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.sendPacket(PlayerConnection.java:1048) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:300) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.d(EntityTrackerEntry.java:265) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:191) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:179) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:804) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 287.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:254) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:693) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	... 29 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field tracker with the type net.minecraft.server.v1_9_R1.Entity in net.minecraft.server.v1_9_R1.EntityTrackerEntry
	at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:369) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:239) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:693) ~[ProtocolLib.jar:3.7-SNAPSHOT-b232]
	... 29 more
[16:03:04] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_9_R1.PacketPlayOutEntityMetadata@971a4db[
    a=287
    b=[net.minecraft.server.v1_9_R1.DataWatcher$Item@470dddd9, net.minecraft.server.v1_9_R1.DataWatcher$Item@65976d4f, net.minecraft.server.v1_9_R1.DataWatcher$Item@70972695, net.minecraft.server.v1_9_R1.DataWatcher$Item@7d186c7b, net.minecraft.server.v1_9_R1.DataWatcher$Item@54528514, net.minecraft.server.v1_9_R1.DataWatcher$Item@af167c4, net.minecraft.server.v1_9_R1.DataWatcher$Item@439b4b81, net.minecraft.server.v1_9_R1.DataWatcher$Item@7dde9c3d, net.minecraft.server.v1_9_R1.DataWatcher$Item@3d64dcb7, net.minecraft.server.v1_9_R1.DataWatcher$Item@3c2a5398, net.minecraft.server.v1_9_R1.DataWatcher$Item@25f4c0df, net.minecraft.server.v1_9_R1.DataWatcher$Item@2cc29f28, net.minecraft.server.v1_9_R1.DataWatcher$Item@37586f63, net.minecraft.server.v1_9_R1.DataWatcher$Item@59005c83]
  ]

```

**Comment by mibby** [comment]
ProtocolLib 1.9 update is out. :D

**Comment by NavidK0** [comment]
Datawatchers are still broken in ProtocolLib, I need to wait for that feature as well.

**Comment by mibby** [comment]
Hopefully soon. :( 

Using ProtocolLib dev 236
```
[19:32:47] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v9.0.0 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_74]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_74]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.initializeMethods(WrappedDataWatcher.java:836) ~[?:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.initialize(WrappedDataWatcher.java:742) ~[?:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.<init>(WrappedDataWatcher.java:255) ~[?:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.getEntityWatcher(WrappedDataWatcher.java:691) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:225) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:76) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot.jar:git-Spigot-1a196e1-92602ad]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-1a196e1-92602ad]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

**Comment by NavidK0** [comment]
https://github.com/libraryaddict/LibsDisguises/issues/98

**Comment by NavidK0** [comment]
If you would, please post your 1.9 related issues here: https://github.com/libraryaddict/LibsDisguises/issues/98

That would help me out greatly, thanks.
